// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/common/v1/common_enums.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensitivityClass int32

const (
	SensitivityClass_SENSITIVITY_CLASS_UNSPECIFIED  SensitivityClass = 0
	SensitivityClass_SENSITIVITY_CLASS_PUBLIC       SensitivityClass = 1
	SensitivityClass_SENSITIVITY_CLASS_INTERNAL     SensitivityClass = 2
	SensitivityClass_SENSITIVITY_CLASS_CONFIDENTIAL SensitivityClass = 3
	SensitivityClass_SENSITIVITY_CLASS_PII          SensitivityClass = 4
	SensitivityClass_SENSITIVITY_CLASS_SECRET       SensitivityClass = 5
)

// Enum value maps for SensitivityClass.
var (
	SensitivityClass_name = map[int32]string{
		0: "SENSITIVITY_CLASS_UNSPECIFIED",
		1: "SENSITIVITY_CLASS_PUBLIC",
		2: "SENSITIVITY_CLASS_INTERNAL",
		3: "SENSITIVITY_CLASS_CONFIDENTIAL",
		4: "SENSITIVITY_CLASS_PII",
		5: "SENSITIVITY_CLASS_SECRET",
	}
	SensitivityClass_value = map[string]int32{
		"SENSITIVITY_CLASS_UNSPECIFIED":  0,
		"SENSITIVITY_CLASS_PUBLIC":       1,
		"SENSITIVITY_CLASS_INTERNAL":     2,
		"SENSITIVITY_CLASS_CONFIDENTIAL": 3,
		"SENSITIVITY_CLASS_PII":          4,
		"SENSITIVITY_CLASS_SECRET":       5,
	}
)

func (x SensitivityClass) Enum() *SensitivityClass {
	p := new(SensitivityClass)
	*p = x
	return p
}

func (x SensitivityClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SensitivityClass) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_common_v1_common_enums_proto_enumTypes[0].Descriptor()
}

func (SensitivityClass) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_common_v1_common_enums_proto_enumTypes[0]
}

func (x SensitivityClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SensitivityClass.Descriptor instead.
func (SensitivityClass) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDescGZIP(), []int{0}
}

type RetryHint int32

const (
	RetryHint_RETRY_HINT_UNSPECIFIED   RetryHint = 0
	RetryHint_RETRY_HINT_RETRYABLE     RetryHint = 1
	RetryHint_RETRY_HINT_NOT_RETRYABLE RetryHint = 2
	RetryHint_RETRY_HINT_UNKNOWN       RetryHint = 3
)

// Enum value maps for RetryHint.
var (
	RetryHint_name = map[int32]string{
		0: "RETRY_HINT_UNSPECIFIED",
		1: "RETRY_HINT_RETRYABLE",
		2: "RETRY_HINT_NOT_RETRYABLE",
		3: "RETRY_HINT_UNKNOWN",
	}
	RetryHint_value = map[string]int32{
		"RETRY_HINT_UNSPECIFIED":   0,
		"RETRY_HINT_RETRYABLE":     1,
		"RETRY_HINT_NOT_RETRYABLE": 2,
		"RETRY_HINT_UNKNOWN":       3,
	}
)

func (x RetryHint) Enum() *RetryHint {
	p := new(RetryHint)
	*p = x
	return p
}

func (x RetryHint) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetryHint) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_common_v1_common_enums_proto_enumTypes[1].Descriptor()
}

func (RetryHint) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_common_v1_common_enums_proto_enumTypes[1]
}

func (x RetryHint) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetryHint.Descriptor instead.
func (RetryHint) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDescGZIP(), []int{1}
}

type DedupeScope int32

const (
	DedupeScope_DEDUPE_SCOPE_UNSPECIFIED  DedupeScope = 0
	DedupeScope_DEDUPE_SCOPE_TENANT       DedupeScope = 1
	DedupeScope_DEDUPE_SCOPE_RECIPIENT    DedupeScope = 2
	DedupeScope_DEDUPE_SCOPE_SOURCE_EVENT DedupeScope = 3
	DedupeScope_DEDUPE_SCOPE_CAMPAIGN     DedupeScope = 4
	DedupeScope_DEDUPE_SCOPE_CHANNEL      DedupeScope = 5
)

// Enum value maps for DedupeScope.
var (
	DedupeScope_name = map[int32]string{
		0: "DEDUPE_SCOPE_UNSPECIFIED",
		1: "DEDUPE_SCOPE_TENANT",
		2: "DEDUPE_SCOPE_RECIPIENT",
		3: "DEDUPE_SCOPE_SOURCE_EVENT",
		4: "DEDUPE_SCOPE_CAMPAIGN",
		5: "DEDUPE_SCOPE_CHANNEL",
	}
	DedupeScope_value = map[string]int32{
		"DEDUPE_SCOPE_UNSPECIFIED":  0,
		"DEDUPE_SCOPE_TENANT":       1,
		"DEDUPE_SCOPE_RECIPIENT":    2,
		"DEDUPE_SCOPE_SOURCE_EVENT": 3,
		"DEDUPE_SCOPE_CAMPAIGN":     4,
		"DEDUPE_SCOPE_CHANNEL":      5,
	}
)

func (x DedupeScope) Enum() *DedupeScope {
	p := new(DedupeScope)
	*p = x
	return p
}

func (x DedupeScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DedupeScope) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_common_v1_common_enums_proto_enumTypes[2].Descriptor()
}

func (DedupeScope) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_common_v1_common_enums_proto_enumTypes[2]
}

func (x DedupeScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DedupeScope.Descriptor instead.
func (DedupeScope) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDescGZIP(), []int{2}
}

var File_sh_whoa_sutradhar_common_v1_common_enums_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDesc = "" +
	"\n" +
	".sh/whoa/sutradhar/common/v1/common_enums.proto\x12\x1bsh.whoa.sutradhar.common.v1*\xd0\x01\n" +
	"\x10SensitivityClass\x12!\n" +
	"\x1dSENSITIVITY_CLASS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SENSITIVITY_CLASS_PUBLIC\x10\x01\x12\x1e\n" +
	"\x1aSENSITIVITY_CLASS_INTERNAL\x10\x02\x12\"\n" +
	"\x1eSENSITIVITY_CLASS_CONFIDENTIAL\x10\x03\x12\x19\n" +
	"\x15SENSITIVITY_CLASS_PII\x10\x04\x12\x1c\n" +
	"\x18SENSITIVITY_CLASS_SECRET\x10\x05*w\n" +
	"\tRetryHint\x12\x1a\n" +
	"\x16RETRY_HINT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RETRY_HINT_RETRYABLE\x10\x01\x12\x1c\n" +
	"\x18RETRY_HINT_NOT_RETRYABLE\x10\x02\x12\x16\n" +
	"\x12RETRY_HINT_UNKNOWN\x10\x03*\xb4\x01\n" +
	"\vDedupeScope\x12\x1c\n" +
	"\x18DEDUPE_SCOPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DEDUPE_SCOPE_TENANT\x10\x01\x12\x1a\n" +
	"\x16DEDUPE_SCOPE_RECIPIENT\x10\x02\x12\x1d\n" +
	"\x19DEDUPE_SCOPE_SOURCE_EVENT\x10\x03\x12\x19\n" +
	"\x15DEDUPE_SCOPE_CAMPAIGN\x10\x04\x12\x18\n" +
	"\x14DEDUPE_SCOPE_CHANNEL\x10\x05B\x93\x02\n" +
	"\x1fcom.sh.whoa.sutradhar.common.v1B\x10CommonEnumsProtoP\x01ZMgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/common/v1;commonv1\xa2\x02\x04SWSC\xaa\x02\x1bSh.Whoa.Sutradhar.Common.V1\xca\x02\x1bSh\\Whoa\\Sutradhar\\Common\\V1\xe2\x02'Sh\\Whoa\\Sutradhar\\Common\\V1\\GPBMetadata\xea\x02\x1fSh::Whoa::Sutradhar::Common::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDesc), len(file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDescData
}

var file_sh_whoa_sutradhar_common_v1_common_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sh_whoa_sutradhar_common_v1_common_enums_proto_goTypes = []any{
	(SensitivityClass)(0), // 0: sh.whoa.sutradhar.common.v1.SensitivityClass
	(RetryHint)(0),        // 1: sh.whoa.sutradhar.common.v1.RetryHint
	(DedupeScope)(0),      // 2: sh.whoa.sutradhar.common.v1.DedupeScope
}
var file_sh_whoa_sutradhar_common_v1_common_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_common_v1_common_enums_proto_init() }
func file_sh_whoa_sutradhar_common_v1_common_enums_proto_init() {
	if File_sh_whoa_sutradhar_common_v1_common_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDesc), len(file_sh_whoa_sutradhar_common_v1_common_enums_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_common_v1_common_enums_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_common_v1_common_enums_proto_depIdxs,
		EnumInfos:         file_sh_whoa_sutradhar_common_v1_common_enums_proto_enumTypes,
	}.Build()
	File_sh_whoa_sutradhar_common_v1_common_enums_proto = out.File
	file_sh_whoa_sutradhar_common_v1_common_enums_proto_goTypes = nil
	file_sh_whoa_sutradhar_common_v1_common_enums_proto_depIdxs = nil
}
