// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/common/v1/failure_context.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailureCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailureCode) Reset() {
	*x = FailureCode{}
	mi := &file_sh_whoa_sutradhar_common_v1_failure_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureCode) ProtoMessage() {}

func (x *FailureCode) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_common_v1_failure_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureCode.ProtoReflect.Descriptor instead.
func (*FailureCode) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDescGZIP(), []int{0}
}

func (x *FailureCode) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *FailureCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type FailureContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FailureCode    *FailureCode           `protobuf:"bytes,1,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	FailureMessage string                 `protobuf:"bytes,2,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	Retryable      bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	RetryHint      RetryHint              `protobuf:"varint,4,opt,name=retry_hint,json=retryHint,proto3,enum=sh.whoa.sutradhar.common.v1.RetryHint" json:"retry_hint,omitempty"`
	AttemptNumber  int32                  `protobuf:"varint,5,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	MaxAttempts    int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	FailedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	SourceService  string                 `protobuf:"bytes,8,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	Details        *Metadata              `protobuf:"bytes,9,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FailureContext) Reset() {
	*x = FailureContext{}
	mi := &file_sh_whoa_sutradhar_common_v1_failure_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureContext) ProtoMessage() {}

func (x *FailureContext) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_common_v1_failure_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureContext.ProtoReflect.Descriptor instead.
func (*FailureContext) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDescGZIP(), []int{1}
}

func (x *FailureContext) GetFailureCode() *FailureCode {
	if x != nil {
		return x.FailureCode
	}
	return nil
}

func (x *FailureContext) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *FailureContext) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *FailureContext) GetRetryHint() RetryHint {
	if x != nil {
		return x.RetryHint
	}
	return RetryHint_RETRY_HINT_UNSPECIFIED
}

func (x *FailureContext) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *FailureContext) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *FailureContext) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *FailureContext) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *FailureContext) GetDetails() *Metadata {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_sh_whoa_sutradhar_common_v1_failure_context_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDesc = "" +
	"\n" +
	"1sh/whoa/sutradhar/common/v1/failure_context.proto\x12\x1bsh.whoa.sutradhar.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.sh/whoa/sutradhar/common/v1/common_enums.proto\x1a*sh/whoa/sutradhar/common/v1/metadata.proto\"?\n" +
	"\vFailureCode\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\xd6\x03\n" +
	"\x0eFailureContext\x12K\n" +
	"\ffailure_code\x18\x01 \x01(\v2(.sh.whoa.sutradhar.common.v1.FailureCodeR\vfailureCode\x12'\n" +
	"\x0ffailure_message\x18\x02 \x01(\tR\x0efailureMessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12E\n" +
	"\n" +
	"retry_hint\x18\x04 \x01(\x0e2&.sh.whoa.sutradhar.common.v1.RetryHintR\tretryHint\x12%\n" +
	"\x0eattempt_number\x18\x05 \x01(\x05R\rattemptNumber\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x127\n" +
	"\tfailed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\x12%\n" +
	"\x0esource_service\x18\b \x01(\tR\rsourceService\x12?\n" +
	"\adetails\x18\t \x01(\v2%.sh.whoa.sutradhar.common.v1.MetadataR\adetailsB\x96\x02\n" +
	"\x1fcom.sh.whoa.sutradhar.common.v1B\x13FailureContextProtoP\x01ZMgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/common/v1;commonv1\xa2\x02\x04SWSC\xaa\x02\x1bSh.Whoa.Sutradhar.Common.V1\xca\x02\x1bSh\\Whoa\\Sutradhar\\Common\\V1\xe2\x02'Sh\\Whoa\\Sutradhar\\Common\\V1\\GPBMetadata\xea\x02\x1fSh::Whoa::Sutradhar::Common::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDesc), len(file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDescData
}

var file_sh_whoa_sutradhar_common_v1_failure_context_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sh_whoa_sutradhar_common_v1_failure_context_proto_goTypes = []any{
	(*FailureCode)(nil),           // 0: sh.whoa.sutradhar.common.v1.FailureCode
	(*FailureContext)(nil),        // 1: sh.whoa.sutradhar.common.v1.FailureContext
	(RetryHint)(0),                // 2: sh.whoa.sutradhar.common.v1.RetryHint
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*Metadata)(nil),              // 4: sh.whoa.sutradhar.common.v1.Metadata
}
var file_sh_whoa_sutradhar_common_v1_failure_context_proto_depIdxs = []int32{
	0, // 0: sh.whoa.sutradhar.common.v1.FailureContext.failure_code:type_name -> sh.whoa.sutradhar.common.v1.FailureCode
	2, // 1: sh.whoa.sutradhar.common.v1.FailureContext.retry_hint:type_name -> sh.whoa.sutradhar.common.v1.RetryHint
	3, // 2: sh.whoa.sutradhar.common.v1.FailureContext.failed_at:type_name -> google.protobuf.Timestamp
	4, // 3: sh.whoa.sutradhar.common.v1.FailureContext.details:type_name -> sh.whoa.sutradhar.common.v1.Metadata
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_common_v1_failure_context_proto_init() }
func file_sh_whoa_sutradhar_common_v1_failure_context_proto_init() {
	if File_sh_whoa_sutradhar_common_v1_failure_context_proto != nil {
		return
	}
	file_sh_whoa_sutradhar_common_v1_common_enums_proto_init()
	file_sh_whoa_sutradhar_common_v1_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDesc), len(file_sh_whoa_sutradhar_common_v1_failure_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_common_v1_failure_context_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_common_v1_failure_context_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_common_v1_failure_context_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_common_v1_failure_context_proto = out.File
	file_sh_whoa_sutradhar_common_v1_failure_context_proto_goTypes = nil
	file_sh_whoa_sutradhar_common_v1_failure_context_proto_depIdxs = nil
}
