// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/common/v1/idempotency_context.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdempotencyContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceSystem   string                 `protobuf:"bytes,1,opt,name=source_system,json=sourceSystem,proto3" json:"source_system,omitempty"`
	SourceEventId  string                 `protobuf:"bytes,2,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	DedupeScope    DedupeScope            `protobuf:"varint,4,opt,name=dedupe_scope,json=dedupeScope,proto3,enum=sh.whoa.sutradhar.common.v1.DedupeScope" json:"dedupe_scope,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IdempotencyContext) Reset() {
	*x = IdempotencyContext{}
	mi := &file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotencyContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotencyContext) ProtoMessage() {}

func (x *IdempotencyContext) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotencyContext.ProtoReflect.Descriptor instead.
func (*IdempotencyContext) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_rawDescGZIP(), []int{0}
}

func (x *IdempotencyContext) GetSourceSystem() string {
	if x != nil {
		return x.SourceSystem
	}
	return ""
}

func (x *IdempotencyContext) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *IdempotencyContext) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *IdempotencyContext) GetDedupeScope() DedupeScope {
	if x != nil {
		return x.DedupeScope
	}
	return DedupeScope_DEDUPE_SCOPE_UNSPECIFIED
}

var File_sh_whoa_sutradhar_common_v1_idempotency_context_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_rawDesc = "" +
	"\n" +
	"5sh/whoa/sutradhar/common/v1/idempotency_context.proto\x12\x1bsh.whoa.sutradhar.common.v1\x1a.sh/whoa/sutradhar/common/v1/common_enums.proto\"\xd7\x01\n" +
	"\x12IdempotencyContext\x12#\n" +
	"\rsource_system\x18\x01 \x01(\tR\fsourceSystem\x12&\n" +
	"\x0fsource_event_id\x18\x02 \x01(\tR\rsourceEventId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12K\n" +
	"\fdedupe_scope\x18\x04 \x01(\x0e2(.sh.whoa.sutradhar.common.v1.DedupeScopeR\vdedupeScopeB\x9a\x02\n" +
	"\x1fcom.sh.whoa.sutradhar.common.v1B\x17IdempotencyContextProtoP\x01ZMgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/common/v1;commonv1\xa2\x02\x04SWSC\xaa\x02\x1bSh.Whoa.Sutradhar.Common.V1\xca\x02\x1bSh\\Whoa\\Sutradhar\\Common\\V1\xe2\x02'Sh\\Whoa\\Sutradhar\\Common\\V1\\GPBMetadata\xea\x02\x1fSh::Whoa::Sutradhar::Common::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_rawDesc), len(file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_rawDescData
}

var file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_goTypes = []any{
	(*IdempotencyContext)(nil), // 0: sh.whoa.sutradhar.common.v1.IdempotencyContext
	(DedupeScope)(0),           // 1: sh.whoa.sutradhar.common.v1.DedupeScope
}
var file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_depIdxs = []int32{
	1, // 0: sh.whoa.sutradhar.common.v1.IdempotencyContext.dedupe_scope:type_name -> sh.whoa.sutradhar.common.v1.DedupeScope
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_init() }
func file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_init() {
	if File_sh_whoa_sutradhar_common_v1_idempotency_context_proto != nil {
		return
	}
	file_sh_whoa_sutradhar_common_v1_common_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_rawDesc), len(file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_common_v1_idempotency_context_proto = out.File
	file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_goTypes = nil
	file_sh_whoa_sutradhar_common_v1_idempotency_context_proto_depIdxs = nil
}
