// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/common/v1/metadata.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MetadataEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_sh_whoa_sutradhar_common_v1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_common_v1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetEntries() []*MetadataEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MetadataEntry struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Key         string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Sensitivity SensitivityClass       `protobuf:"varint,2,opt,name=sensitivity,proto3,enum=sh.whoa.sutradhar.common.v1.SensitivityClass" json:"sensitivity,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*MetadataEntry_StringValue
	//	*MetadataEntry_IntValue
	//	*MetadataEntry_BoolValue
	//	*MetadataEntry_DecimalValue
	//	*MetadataEntry_TimestampValue
	Value         isMetadataEntry_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataEntry) Reset() {
	*x = MetadataEntry{}
	mi := &file_sh_whoa_sutradhar_common_v1_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataEntry) ProtoMessage() {}

func (x *MetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_common_v1_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataEntry.ProtoReflect.Descriptor instead.
func (*MetadataEntry) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataEntry) GetSensitivity() SensitivityClass {
	if x != nil {
		return x.Sensitivity
	}
	return SensitivityClass_SENSITIVITY_CLASS_UNSPECIFIED
}

func (x *MetadataEntry) GetValue() isMetadataEntry_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetadataEntry) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*MetadataEntry_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *MetadataEntry) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*MetadataEntry_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *MetadataEntry) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*MetadataEntry_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *MetadataEntry) GetDecimalValue() string {
	if x != nil {
		if x, ok := x.Value.(*MetadataEntry_DecimalValue); ok {
			return x.DecimalValue
		}
	}
	return ""
}

func (x *MetadataEntry) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*MetadataEntry_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

type isMetadataEntry_Value interface {
	isMetadataEntry_Value()
}

type MetadataEntry_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type MetadataEntry_IntValue struct {
	IntValue int64 `protobuf:"varint,4,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MetadataEntry_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type MetadataEntry_DecimalValue struct {
	DecimalValue string `protobuf:"bytes,6,opt,name=decimal_value,json=decimalValue,proto3,oneof"`
}

type MetadataEntry_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

func (*MetadataEntry_StringValue) isMetadataEntry_Value() {}

func (*MetadataEntry_IntValue) isMetadataEntry_Value() {}

func (*MetadataEntry_BoolValue) isMetadataEntry_Value() {}

func (*MetadataEntry_DecimalValue) isMetadataEntry_Value() {}

func (*MetadataEntry_TimestampValue) isMetadataEntry_Value() {}

var File_sh_whoa_sutradhar_common_v1_metadata_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDesc = "" +
	"\n" +
	"*sh/whoa/sutradhar/common/v1/metadata.proto\x12\x1bsh.whoa.sutradhar.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.sh/whoa/sutradhar/common/v1/common_enums.proto\"P\n" +
	"\bMetadata\x12D\n" +
	"\aentries\x18\x01 \x03(\v2*.sh.whoa.sutradhar.common.v1.MetadataEntryR\aentries\"\xce\x02\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12O\n" +
	"\vsensitivity\x18\x02 \x01(\x0e2-.sh.whoa.sutradhar.common.v1.SensitivityClassR\vsensitivity\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x04 \x01(\x03H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x05 \x01(\bH\x00R\tboolValue\x12%\n" +
	"\rdecimal_value\x18\x06 \x01(\tH\x00R\fdecimalValue\x12E\n" +
	"\x0ftimestamp_value\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValueB\a\n" +
	"\x05valueB\x90\x02\n" +
	"\x1fcom.sh.whoa.sutradhar.common.v1B\rMetadataProtoP\x01ZMgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/common/v1;commonv1\xa2\x02\x04SWSC\xaa\x02\x1bSh.Whoa.Sutradhar.Common.V1\xca\x02\x1bSh\\Whoa\\Sutradhar\\Common\\V1\xe2\x02'Sh\\Whoa\\Sutradhar\\Common\\V1\\GPBMetadata\xea\x02\x1fSh::Whoa::Sutradhar::Common::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDesc), len(file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDescData
}

var file_sh_whoa_sutradhar_common_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sh_whoa_sutradhar_common_v1_metadata_proto_goTypes = []any{
	(*Metadata)(nil),              // 0: sh.whoa.sutradhar.common.v1.Metadata
	(*MetadataEntry)(nil),         // 1: sh.whoa.sutradhar.common.v1.MetadataEntry
	(SensitivityClass)(0),         // 2: sh.whoa.sutradhar.common.v1.SensitivityClass
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_sh_whoa_sutradhar_common_v1_metadata_proto_depIdxs = []int32{
	1, // 0: sh.whoa.sutradhar.common.v1.Metadata.entries:type_name -> sh.whoa.sutradhar.common.v1.MetadataEntry
	2, // 1: sh.whoa.sutradhar.common.v1.MetadataEntry.sensitivity:type_name -> sh.whoa.sutradhar.common.v1.SensitivityClass
	3, // 2: sh.whoa.sutradhar.common.v1.MetadataEntry.timestamp_value:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_common_v1_metadata_proto_init() }
func file_sh_whoa_sutradhar_common_v1_metadata_proto_init() {
	if File_sh_whoa_sutradhar_common_v1_metadata_proto != nil {
		return
	}
	file_sh_whoa_sutradhar_common_v1_common_enums_proto_init()
	file_sh_whoa_sutradhar_common_v1_metadata_proto_msgTypes[1].OneofWrappers = []any{
		(*MetadataEntry_StringValue)(nil),
		(*MetadataEntry_IntValue)(nil),
		(*MetadataEntry_BoolValue)(nil),
		(*MetadataEntry_DecimalValue)(nil),
		(*MetadataEntry_TimestampValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDesc), len(file_sh_whoa_sutradhar_common_v1_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_common_v1_metadata_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_common_v1_metadata_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_common_v1_metadata_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_common_v1_metadata_proto = out.File
	file_sh_whoa_sutradhar_common_v1_metadata_proto_goTypes = nil
	file_sh_whoa_sutradhar_common_v1_metadata_proto_depIdxs = nil
}
