// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/common/v1/tenant_context.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantContext) Reset() {
	*x = TenantContext{}
	mi := &file_sh_whoa_sutradhar_common_v1_tenant_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantContext) ProtoMessage() {}

func (x *TenantContext) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_common_v1_tenant_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantContext.ProtoReflect.Descriptor instead.
func (*TenantContext) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_common_v1_tenant_context_proto_rawDescGZIP(), []int{0}
}

func (x *TenantContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantContext) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *TenantContext) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_sh_whoa_sutradhar_common_v1_tenant_context_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_common_v1_tenant_context_proto_rawDesc = "" +
	"\n" +
	"0sh/whoa/sutradhar/common/v1/tenant_context.proto\x12\x1bsh.whoa.sutradhar.common.v1\"f\n" +
	"\rTenantContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06regionB\x95\x02\n" +
	"\x1fcom.sh.whoa.sutradhar.common.v1B\x12TenantContextProtoP\x01ZMgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/common/v1;commonv1\xa2\x02\x04SWSC\xaa\x02\x1bSh.Whoa.Sutradhar.Common.V1\xca\x02\x1bSh\\Whoa\\Sutradhar\\Common\\V1\xe2\x02'Sh\\Whoa\\Sutradhar\\Common\\V1\\GPBMetadata\xea\x02\x1fSh::Whoa::Sutradhar::Common::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_common_v1_tenant_context_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_common_v1_tenant_context_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_common_v1_tenant_context_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_common_v1_tenant_context_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_common_v1_tenant_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_common_v1_tenant_context_proto_rawDesc), len(file_sh_whoa_sutradhar_common_v1_tenant_context_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_common_v1_tenant_context_proto_rawDescData
}

var file_sh_whoa_sutradhar_common_v1_tenant_context_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sh_whoa_sutradhar_common_v1_tenant_context_proto_goTypes = []any{
	(*TenantContext)(nil), // 0: sh.whoa.sutradhar.common.v1.TenantContext
}
var file_sh_whoa_sutradhar_common_v1_tenant_context_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_common_v1_tenant_context_proto_init() }
func file_sh_whoa_sutradhar_common_v1_tenant_context_proto_init() {
	if File_sh_whoa_sutradhar_common_v1_tenant_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_common_v1_tenant_context_proto_rawDesc), len(file_sh_whoa_sutradhar_common_v1_tenant_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_common_v1_tenant_context_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_common_v1_tenant_context_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_common_v1_tenant_context_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_common_v1_tenant_context_proto = out.File
	file_sh_whoa_sutradhar_common_v1_tenant_context_proto_goTypes = nil
	file_sh_whoa_sutradhar_common_v1_tenant_context_proto_depIdxs = nil
}
