// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/common/v1/trace_context.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TraceContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traceparent   string                 `protobuf:"bytes,1,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	Tracestate    string                 `protobuf:"bytes,2,opt,name=tracestate,proto3" json:"tracestate,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId   string                 `protobuf:"bytes,4,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceContext) Reset() {
	*x = TraceContext{}
	mi := &file_sh_whoa_sutradhar_common_v1_trace_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceContext) ProtoMessage() {}

func (x *TraceContext) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_common_v1_trace_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceContext.ProtoReflect.Descriptor instead.
func (*TraceContext) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_common_v1_trace_context_proto_rawDescGZIP(), []int{0}
}

func (x *TraceContext) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *TraceContext) GetTracestate() string {
	if x != nil {
		return x.Tracestate
	}
	return ""
}

func (x *TraceContext) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TraceContext) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *TraceContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_sh_whoa_sutradhar_common_v1_trace_context_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_common_v1_trace_context_proto_rawDesc = "" +
	"\n" +
	"/sh/whoa/sutradhar/common/v1/trace_context.proto\x12\x1bsh.whoa.sutradhar.common.v1\"\xb9\x01\n" +
	"\fTraceContext\x12 \n" +
	"\vtraceparent\x18\x01 \x01(\tR\vtraceparent\x12\x1e\n" +
	"\n" +
	"tracestate\x18\x02 \x01(\tR\n" +
	"tracestate\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\x04 \x01(\tR\vcausationId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestIdB\x94\x02\n" +
	"\x1fcom.sh.whoa.sutradhar.common.v1B\x11TraceContextProtoP\x01ZMgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/common/v1;commonv1\xa2\x02\x04SWSC\xaa\x02\x1bSh.Whoa.Sutradhar.Common.V1\xca\x02\x1bSh\\Whoa\\Sutradhar\\Common\\V1\xe2\x02'Sh\\Whoa\\Sutradhar\\Common\\V1\\GPBMetadata\xea\x02\x1fSh::Whoa::Sutradhar::Common::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_common_v1_trace_context_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_common_v1_trace_context_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_common_v1_trace_context_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_common_v1_trace_context_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_common_v1_trace_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_common_v1_trace_context_proto_rawDesc), len(file_sh_whoa_sutradhar_common_v1_trace_context_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_common_v1_trace_context_proto_rawDescData
}

var file_sh_whoa_sutradhar_common_v1_trace_context_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sh_whoa_sutradhar_common_v1_trace_context_proto_goTypes = []any{
	(*TraceContext)(nil), // 0: sh.whoa.sutradhar.common.v1.TraceContext
}
var file_sh_whoa_sutradhar_common_v1_trace_context_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_common_v1_trace_context_proto_init() }
func file_sh_whoa_sutradhar_common_v1_trace_context_proto_init() {
	if File_sh_whoa_sutradhar_common_v1_trace_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_common_v1_trace_context_proto_rawDesc), len(file_sh_whoa_sutradhar_common_v1_trace_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_common_v1_trace_context_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_common_v1_trace_context_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_common_v1_trace_context_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_common_v1_trace_context_proto = out.File
	file_sh_whoa_sutradhar_common_v1_trace_context_proto_goTypes = nil
	file_sh_whoa_sutradhar_common_v1_trace_context_proto_depIdxs = nil
}
