// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/provider/v1/delivery_command.proto

package providerv1

import (
	v1 "github.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/common/v1"
	v11 "github.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/notification/v1"
	v12 "github.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/template/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryCommand struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	TenantContext   *v1.TenantContext        `protobuf:"bytes,1,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	TraceContext    *v1.TraceContext         `protobuf:"bytes,2,opt,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty"`
	RequestId       string                   `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DeliveryTaskId  string                   `protobuf:"bytes,4,opt,name=delivery_task_id,json=deliveryTaskId,proto3" json:"delivery_task_id,omitempty"`
	AttemptId       string                   `protobuf:"bytes,5,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Channel         v11.NotificationChannel  `protobuf:"varint,6,opt,name=channel,proto3,enum=sh.whoa.sutradhar.notification.v1.NotificationChannel" json:"channel,omitempty"`
	Priority        v11.NotificationPriority `protobuf:"varint,7,opt,name=priority,proto3,enum=sh.whoa.sutradhar.notification.v1.NotificationPriority" json:"priority,omitempty"`
	RenderedPayload *v12.RenderedPayload     `protobuf:"bytes,8,opt,name=rendered_payload,json=renderedPayload,proto3" json:"rendered_payload,omitempty"`
	Target          *v11.NotificationTarget  `protobuf:"bytes,9,opt,name=target,proto3" json:"target,omitempty"`
	Provider        ProviderType             `protobuf:"varint,10,opt,name=provider,proto3,enum=sh.whoa.sutradhar.provider.v1.ProviderType" json:"provider,omitempty"`
	ProviderSubId   string                   `protobuf:"bytes,11,opt,name=provider_sub_id,json=providerSubId,proto3" json:"provider_sub_id,omitempty"`
	Metadata        *v1.Metadata             `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeliveryCommand) Reset() {
	*x = DeliveryCommand{}
	mi := &file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryCommand) ProtoMessage() {}

func (x *DeliveryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryCommand.ProtoReflect.Descriptor instead.
func (*DeliveryCommand) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryCommand) GetTenantContext() *v1.TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *DeliveryCommand) GetTraceContext() *v1.TraceContext {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

func (x *DeliveryCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeliveryCommand) GetDeliveryTaskId() string {
	if x != nil {
		return x.DeliveryTaskId
	}
	return ""
}

func (x *DeliveryCommand) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *DeliveryCommand) GetChannel() v11.NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return v11.NotificationChannel(0)
}

func (x *DeliveryCommand) GetPriority() v11.NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return v11.NotificationPriority(0)
}

func (x *DeliveryCommand) GetRenderedPayload() *v12.RenderedPayload {
	if x != nil {
		return x.RenderedPayload
	}
	return nil
}

func (x *DeliveryCommand) GetTarget() *v11.NotificationTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DeliveryCommand) GetProvider() ProviderType {
	if x != nil {
		return x.Provider
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *DeliveryCommand) GetProviderSubId() string {
	if x != nil {
		return x.ProviderSubId
	}
	return ""
}

func (x *DeliveryCommand) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_sh_whoa_sutradhar_provider_v1_delivery_command_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_rawDesc = "" +
	"\n" +
	"4sh/whoa/sutradhar/provider/v1/delivery_command.proto\x12\x1dsh.whoa.sutradhar.provider.v1\x1a*sh/whoa/sutradhar/common/v1/metadata.proto\x1a0sh/whoa/sutradhar/common/v1/tenant_context.proto\x1a/sh/whoa/sutradhar/common/v1/trace_context.proto\x1a:sh/whoa/sutradhar/notification/v1/notification_enums.proto\x1a;sh/whoa/sutradhar/notification/v1/notification_target.proto\x1a2sh/whoa/sutradhar/provider/v1/provider_enums.proto\x1a1sh/whoa/sutradhar/template/v1/render_result.proto\"\xa1\x06\n" +
	"\x0fDeliveryCommand\x12Q\n" +
	"\x0etenant_context\x18\x01 \x01(\v2*.sh.whoa.sutradhar.common.v1.TenantContextR\rtenantContext\x12N\n" +
	"\rtrace_context\x18\x02 \x01(\v2).sh.whoa.sutradhar.common.v1.TraceContextR\ftraceContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12(\n" +
	"\x10delivery_task_id\x18\x04 \x01(\tR\x0edeliveryTaskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x05 \x01(\tR\tattemptId\x12P\n" +
	"\achannel\x18\x06 \x01(\x0e26.sh.whoa.sutradhar.notification.v1.NotificationChannelR\achannel\x12S\n" +
	"\bpriority\x18\a \x01(\x0e27.sh.whoa.sutradhar.notification.v1.NotificationPriorityR\bpriority\x12Y\n" +
	"\x10rendered_payload\x18\b \x01(\v2..sh.whoa.sutradhar.template.v1.RenderedPayloadR\x0frenderedPayload\x12M\n" +
	"\x06target\x18\t \x01(\v25.sh.whoa.sutradhar.notification.v1.NotificationTargetR\x06target\x12G\n" +
	"\bprovider\x18\n" +
	" \x01(\x0e2+.sh.whoa.sutradhar.provider.v1.ProviderTypeR\bprovider\x12&\n" +
	"\x0fprovider_sub_id\x18\v \x01(\tR\rproviderSubId\x12A\n" +
	"\bmetadata\x18\f \x01(\v2%.sh.whoa.sutradhar.common.v1.MetadataR\bmetadataB\xa5\x02\n" +
	"!com.sh.whoa.sutradhar.provider.v1B\x14DeliveryCommandProtoP\x01ZQgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/provider/v1;providerv1\xa2\x02\x04SWSP\xaa\x02\x1dSh.Whoa.Sutradhar.Provider.V1\xca\x02\x1dSh\\Whoa\\Sutradhar\\Provider\\V1\xe2\x02)Sh\\Whoa\\Sutradhar\\Provider\\V1\\GPBMetadata\xea\x02!Sh::Whoa::Sutradhar::Provider::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_rawDesc), len(file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_rawDescData
}

var file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_goTypes = []any{
	(*DeliveryCommand)(nil),        // 0: sh.whoa.sutradhar.provider.v1.DeliveryCommand
	(*v1.TenantContext)(nil),       // 1: sh.whoa.sutradhar.common.v1.TenantContext
	(*v1.TraceContext)(nil),        // 2: sh.whoa.sutradhar.common.v1.TraceContext
	(v11.NotificationChannel)(0),   // 3: sh.whoa.sutradhar.notification.v1.NotificationChannel
	(v11.NotificationPriority)(0),  // 4: sh.whoa.sutradhar.notification.v1.NotificationPriority
	(*v12.RenderedPayload)(nil),    // 5: sh.whoa.sutradhar.template.v1.RenderedPayload
	(*v11.NotificationTarget)(nil), // 6: sh.whoa.sutradhar.notification.v1.NotificationTarget
	(ProviderType)(0),              // 7: sh.whoa.sutradhar.provider.v1.ProviderType
	(*v1.Metadata)(nil),            // 8: sh.whoa.sutradhar.common.v1.Metadata
}
var file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_depIdxs = []int32{
	1, // 0: sh.whoa.sutradhar.provider.v1.DeliveryCommand.tenant_context:type_name -> sh.whoa.sutradhar.common.v1.TenantContext
	2, // 1: sh.whoa.sutradhar.provider.v1.DeliveryCommand.trace_context:type_name -> sh.whoa.sutradhar.common.v1.TraceContext
	3, // 2: sh.whoa.sutradhar.provider.v1.DeliveryCommand.channel:type_name -> sh.whoa.sutradhar.notification.v1.NotificationChannel
	4, // 3: sh.whoa.sutradhar.provider.v1.DeliveryCommand.priority:type_name -> sh.whoa.sutradhar.notification.v1.NotificationPriority
	5, // 4: sh.whoa.sutradhar.provider.v1.DeliveryCommand.rendered_payload:type_name -> sh.whoa.sutradhar.template.v1.RenderedPayload
	6, // 5: sh.whoa.sutradhar.provider.v1.DeliveryCommand.target:type_name -> sh.whoa.sutradhar.notification.v1.NotificationTarget
	7, // 6: sh.whoa.sutradhar.provider.v1.DeliveryCommand.provider:type_name -> sh.whoa.sutradhar.provider.v1.ProviderType
	8, // 7: sh.whoa.sutradhar.provider.v1.DeliveryCommand.metadata:type_name -> sh.whoa.sutradhar.common.v1.Metadata
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_init() }
func file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_init() {
	if File_sh_whoa_sutradhar_provider_v1_delivery_command_proto != nil {
		return
	}
	file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_rawDesc), len(file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_provider_v1_delivery_command_proto = out.File
	file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_goTypes = nil
	file_sh_whoa_sutradhar_provider_v1_delivery_command_proto_depIdxs = nil
}
