// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/provider/v1/provider_enums.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderType int32

const (
	ProviderType_PROVIDER_TYPE_UNSPECIFIED     ProviderType = 0
	ProviderType_PROVIDER_TYPE_SENDGRID        ProviderType = 1
	ProviderType_PROVIDER_TYPE_TWILIO          ProviderType = 2
	ProviderType_PROVIDER_TYPE_FCM             ProviderType = 3
	ProviderType_PROVIDER_TYPE_APNS            ProviderType = 4
	ProviderType_PROVIDER_TYPE_GENERIC_WEBHOOK ProviderType = 5
)

// Enum value maps for ProviderType.
var (
	ProviderType_name = map[int32]string{
		0: "PROVIDER_TYPE_UNSPECIFIED",
		1: "PROVIDER_TYPE_SENDGRID",
		2: "PROVIDER_TYPE_TWILIO",
		3: "PROVIDER_TYPE_FCM",
		4: "PROVIDER_TYPE_APNS",
		5: "PROVIDER_TYPE_GENERIC_WEBHOOK",
	}
	ProviderType_value = map[string]int32{
		"PROVIDER_TYPE_UNSPECIFIED":     0,
		"PROVIDER_TYPE_SENDGRID":        1,
		"PROVIDER_TYPE_TWILIO":          2,
		"PROVIDER_TYPE_FCM":             3,
		"PROVIDER_TYPE_APNS":            4,
		"PROVIDER_TYPE_GENERIC_WEBHOOK": 5,
	}
)

func (x ProviderType) Enum() *ProviderType {
	p := new(ProviderType)
	*p = x
	return p
}

func (x ProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_enumTypes[0].Descriptor()
}

func (ProviderType) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_enumTypes[0]
}

func (x ProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderType.Descriptor instead.
func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDescGZIP(), []int{0}
}

type ProviderDeliveryStatus int32

const (
	ProviderDeliveryStatus_PROVIDER_DELIVERY_STATUS_UNSPECIFIED       ProviderDeliveryStatus = 0
	ProviderDeliveryStatus_PROVIDER_DELIVERY_STATUS_ACCEPTED_GATEWAY  ProviderDeliveryStatus = 1
	ProviderDeliveryStatus_PROVIDER_DELIVERY_STATUS_ACCEPTED_PROVIDER ProviderDeliveryStatus = 2
	ProviderDeliveryStatus_PROVIDER_DELIVERY_STATUS_REJECTED_PROVIDER ProviderDeliveryStatus = 3
	ProviderDeliveryStatus_PROVIDER_DELIVERY_STATUS_SENT              ProviderDeliveryStatus = 4
	ProviderDeliveryStatus_PROVIDER_DELIVERY_STATUS_DELIVERED         ProviderDeliveryStatus = 5
	ProviderDeliveryStatus_PROVIDER_DELIVERY_STATUS_BOUNCED           ProviderDeliveryStatus = 6
	ProviderDeliveryStatus_PROVIDER_DELIVERY_STATUS_FAILED_RETRYABLE  ProviderDeliveryStatus = 7
	ProviderDeliveryStatus_PROVIDER_DELIVERY_STATUS_FAILED_FINAL      ProviderDeliveryStatus = 8
	ProviderDeliveryStatus_PROVIDER_DELIVERY_STATUS_TIMED_OUT         ProviderDeliveryStatus = 9
)

// Enum value maps for ProviderDeliveryStatus.
var (
	ProviderDeliveryStatus_name = map[int32]string{
		0: "PROVIDER_DELIVERY_STATUS_UNSPECIFIED",
		1: "PROVIDER_DELIVERY_STATUS_ACCEPTED_GATEWAY",
		2: "PROVIDER_DELIVERY_STATUS_ACCEPTED_PROVIDER",
		3: "PROVIDER_DELIVERY_STATUS_REJECTED_PROVIDER",
		4: "PROVIDER_DELIVERY_STATUS_SENT",
		5: "PROVIDER_DELIVERY_STATUS_DELIVERED",
		6: "PROVIDER_DELIVERY_STATUS_BOUNCED",
		7: "PROVIDER_DELIVERY_STATUS_FAILED_RETRYABLE",
		8: "PROVIDER_DELIVERY_STATUS_FAILED_FINAL",
		9: "PROVIDER_DELIVERY_STATUS_TIMED_OUT",
	}
	ProviderDeliveryStatus_value = map[string]int32{
		"PROVIDER_DELIVERY_STATUS_UNSPECIFIED":       0,
		"PROVIDER_DELIVERY_STATUS_ACCEPTED_GATEWAY":  1,
		"PROVIDER_DELIVERY_STATUS_ACCEPTED_PROVIDER": 2,
		"PROVIDER_DELIVERY_STATUS_REJECTED_PROVIDER": 3,
		"PROVIDER_DELIVERY_STATUS_SENT":              4,
		"PROVIDER_DELIVERY_STATUS_DELIVERED":         5,
		"PROVIDER_DELIVERY_STATUS_BOUNCED":           6,
		"PROVIDER_DELIVERY_STATUS_FAILED_RETRYABLE":  7,
		"PROVIDER_DELIVERY_STATUS_FAILED_FINAL":      8,
		"PROVIDER_DELIVERY_STATUS_TIMED_OUT":         9,
	}
)

func (x ProviderDeliveryStatus) Enum() *ProviderDeliveryStatus {
	p := new(ProviderDeliveryStatus)
	*p = x
	return p
}

func (x ProviderDeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderDeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_enumTypes[1].Descriptor()
}

func (ProviderDeliveryStatus) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_enumTypes[1]
}

func (x ProviderDeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderDeliveryStatus.Descriptor instead.
func (ProviderDeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDescGZIP(), []int{1}
}

var File_sh_whoa_sutradhar_provider_v1_provider_enums_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDesc = "" +
	"\n" +
	"2sh/whoa/sutradhar/provider/v1/provider_enums.proto\x12\x1dsh.whoa.sutradhar.provider.v1*\xb5\x01\n" +
	"\fProviderType\x12\x1d\n" +
	"\x19PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROVIDER_TYPE_SENDGRID\x10\x01\x12\x18\n" +
	"\x14PROVIDER_TYPE_TWILIO\x10\x02\x12\x15\n" +
	"\x11PROVIDER_TYPE_FCM\x10\x03\x12\x16\n" +
	"\x12PROVIDER_TYPE_APNS\x10\x04\x12!\n" +
	"\x1dPROVIDER_TYPE_GENERIC_WEBHOOK\x10\x05*\xc4\x03\n" +
	"\x16ProviderDeliveryStatus\x12(\n" +
	"$PROVIDER_DELIVERY_STATUS_UNSPECIFIED\x10\x00\x12-\n" +
	")PROVIDER_DELIVERY_STATUS_ACCEPTED_GATEWAY\x10\x01\x12.\n" +
	"*PROVIDER_DELIVERY_STATUS_ACCEPTED_PROVIDER\x10\x02\x12.\n" +
	"*PROVIDER_DELIVERY_STATUS_REJECTED_PROVIDER\x10\x03\x12!\n" +
	"\x1dPROVIDER_DELIVERY_STATUS_SENT\x10\x04\x12&\n" +
	"\"PROVIDER_DELIVERY_STATUS_DELIVERED\x10\x05\x12$\n" +
	" PROVIDER_DELIVERY_STATUS_BOUNCED\x10\x06\x12-\n" +
	")PROVIDER_DELIVERY_STATUS_FAILED_RETRYABLE\x10\a\x12)\n" +
	"%PROVIDER_DELIVERY_STATUS_FAILED_FINAL\x10\b\x12&\n" +
	"\"PROVIDER_DELIVERY_STATUS_TIMED_OUT\x10\tB\xa3\x02\n" +
	"!com.sh.whoa.sutradhar.provider.v1B\x12ProviderEnumsProtoP\x01ZQgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/provider/v1;providerv1\xa2\x02\x04SWSP\xaa\x02\x1dSh.Whoa.Sutradhar.Provider.V1\xca\x02\x1dSh\\Whoa\\Sutradhar\\Provider\\V1\xe2\x02)Sh\\Whoa\\Sutradhar\\Provider\\V1\\GPBMetadata\xea\x02!Sh::Whoa::Sutradhar::Provider::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDesc), len(file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDescData
}

var file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_goTypes = []any{
	(ProviderType)(0),           // 0: sh.whoa.sutradhar.provider.v1.ProviderType
	(ProviderDeliveryStatus)(0), // 1: sh.whoa.sutradhar.provider.v1.ProviderDeliveryStatus
}
var file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_init() }
func file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_init() {
	if File_sh_whoa_sutradhar_provider_v1_provider_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDesc), len(file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_depIdxs,
		EnumInfos:         file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_enumTypes,
	}.Build()
	File_sh_whoa_sutradhar_provider_v1_provider_enums_proto = out.File
	file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_goTypes = nil
	file_sh_whoa_sutradhar_provider_v1_provider_enums_proto_depIdxs = nil
}
