// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/notification/v1/lifecycle_event.proto

package notificationv1

import (
	v1 "github.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcceptedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      NotificationPriority   `protobuf:"varint,1,opt,name=priority,proto3,enum=sh.whoa.sutradhar.notification.v1.NotificationPriority" json:"priority,omitempty"`
	Channel       NotificationChannel    `protobuf:"varint,2,opt,name=channel,proto3,enum=sh.whoa.sutradhar.notification.v1.NotificationChannel" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedDetails) Reset() {
	*x = AcceptedDetails{}
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedDetails) ProtoMessage() {}

func (x *AcceptedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedDetails.ProtoReflect.Descriptor instead.
func (*AcceptedDetails) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptedDetails) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *AcceptedDetails) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED
}

type DuplicateDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExistingRequestId string                 `protobuf:"bytes,1,opt,name=existing_request_id,json=existingRequestId,proto3" json:"existing_request_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DuplicateDetails) Reset() {
	*x = DuplicateDetails{}
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateDetails) ProtoMessage() {}

func (x *DuplicateDetails) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuplicateDetails.ProtoReflect.Descriptor instead.
func (*DuplicateDetails) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescGZIP(), []int{1}
}

func (x *DuplicateDetails) GetExistingRequestId() string {
	if x != nil {
		return x.ExistingRequestId
	}
	return ""
}

type RejectedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Failure       *v1.FailureContext     `protobuf:"bytes,1,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectedDetails) Reset() {
	*x = RejectedDetails{}
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectedDetails) ProtoMessage() {}

func (x *RejectedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectedDetails.ProtoReflect.Descriptor instead.
func (*RejectedDetails) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescGZIP(), []int{2}
}

func (x *RejectedDetails) GetFailure() *v1.FailureContext {
	if x != nil {
		return x.Failure
	}
	return nil
}

type SuppressedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReasonCode    string                 `protobuf:"bytes,1,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage string                 `protobuf:"bytes,2,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuppressedDetails) Reset() {
	*x = SuppressedDetails{}
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuppressedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuppressedDetails) ProtoMessage() {}

func (x *SuppressedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuppressedDetails.ProtoReflect.Descriptor instead.
func (*SuppressedDetails) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescGZIP(), []int{3}
}

func (x *SuppressedDetails) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *SuppressedDetails) GetReasonMessage() string {
	if x != nil {
		return x.ReasonMessage
	}
	return ""
}

type RenderDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RenderJobId   string                 `protobuf:"bytes,1,opt,name=render_job_id,json=renderJobId,proto3" json:"render_job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderDetails) Reset() {
	*x = RenderDetails{}
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderDetails) ProtoMessage() {}

func (x *RenderDetails) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderDetails.ProtoReflect.Descriptor instead.
func (*RenderDetails) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescGZIP(), []int{4}
}

func (x *RenderDetails) GetRenderJobId() string {
	if x != nil {
		return x.RenderJobId
	}
	return ""
}

type DeliveryDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeliveryTaskId    string                 `protobuf:"bytes,1,opt,name=delivery_task_id,json=deliveryTaskId,proto3" json:"delivery_task_id,omitempty"`
	AttemptId         string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Channel           NotificationChannel    `protobuf:"varint,3,opt,name=channel,proto3,enum=sh.whoa.sutradhar.notification.v1.NotificationChannel" json:"channel,omitempty"`
	Provider          string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderSubId     string                 `protobuf:"bytes,5,opt,name=provider_sub_id,json=providerSubId,proto3" json:"provider_sub_id,omitempty"`
	ProviderMessageId string                 `protobuf:"bytes,6,opt,name=provider_message_id,json=providerMessageId,proto3" json:"provider_message_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeliveryDetails) Reset() {
	*x = DeliveryDetails{}
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryDetails) ProtoMessage() {}

func (x *DeliveryDetails) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryDetails.ProtoReflect.Descriptor instead.
func (*DeliveryDetails) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryDetails) GetDeliveryTaskId() string {
	if x != nil {
		return x.DeliveryTaskId
	}
	return ""
}

func (x *DeliveryDetails) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *DeliveryDetails) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED
}

func (x *DeliveryDetails) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DeliveryDetails) GetProviderSubId() string {
	if x != nil {
		return x.ProviderSubId
	}
	return ""
}

func (x *DeliveryDetails) GetProviderMessageId() string {
	if x != nil {
		return x.ProviderMessageId
	}
	return ""
}

type DlqDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Failure       *v1.FailureContext     `protobuf:"bytes,2,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlqDetails) Reset() {
	*x = DlqDetails{}
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlqDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlqDetails) ProtoMessage() {}

func (x *DlqDetails) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlqDetails.ProtoReflect.Descriptor instead.
func (*DlqDetails) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescGZIP(), []int{6}
}

func (x *DlqDetails) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *DlqDetails) GetFailure() *v1.FailureContext {
	if x != nil {
		return x.Failure
	}
	return nil
}

type ReplayDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OriginalEventId string                 `protobuf:"bytes,1,opt,name=original_event_id,json=originalEventId,proto3" json:"original_event_id,omitempty"`
	ReplayReason    string                 `protobuf:"bytes,2,opt,name=replay_reason,json=replayReason,proto3" json:"replay_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplayDetails) Reset() {
	*x = ReplayDetails{}
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDetails) ProtoMessage() {}

func (x *ReplayDetails) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDetails.ProtoReflect.Descriptor instead.
func (*ReplayDetails) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescGZIP(), []int{7}
}

func (x *ReplayDetails) GetOriginalEventId() string {
	if x != nil {
		return x.OriginalEventId
	}
	return ""
}

func (x *ReplayDetails) GetReplayReason() string {
	if x != nil {
		return x.ReplayReason
	}
	return ""
}

type NotificationLifecycleEvent struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	TenantContext    *v1.TenantContext              `protobuf:"bytes,1,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	TraceContext     *v1.TraceContext               `protobuf:"bytes,2,opt,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty"`
	RequestId        string                         `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	EventId          string                         `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SequenceNumber   int64                          `protobuf:"varint,5,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	CausationEventId string                         `protobuf:"bytes,6,opt,name=causation_event_id,json=causationEventId,proto3" json:"causation_event_id,omitempty"`
	ActorType        LifecycleActorType             `protobuf:"varint,7,opt,name=actor_type,json=actorType,proto3,enum=sh.whoa.sutradhar.notification.v1.LifecycleActorType" json:"actor_type,omitempty"`
	ActorId          string                         `protobuf:"bytes,8,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Type             NotificationLifecycleEventType `protobuf:"varint,9,opt,name=type,proto3,enum=sh.whoa.sutradhar.notification.v1.NotificationLifecycleEventType" json:"type,omitempty"`
	OccurredAt       *timestamppb.Timestamp         `protobuf:"bytes,10,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Metadata         *v1.Metadata                   `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*NotificationLifecycleEvent_Accepted
	//	*NotificationLifecycleEvent_Duplicate
	//	*NotificationLifecycleEvent_Rejected
	//	*NotificationLifecycleEvent_Suppressed
	//	*NotificationLifecycleEvent_Render
	//	*NotificationLifecycleEvent_Delivery
	//	*NotificationLifecycleEvent_Dlq
	//	*NotificationLifecycleEvent_Replay
	Details       isNotificationLifecycleEvent_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationLifecycleEvent) Reset() {
	*x = NotificationLifecycleEvent{}
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationLifecycleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationLifecycleEvent) ProtoMessage() {}

func (x *NotificationLifecycleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationLifecycleEvent.ProtoReflect.Descriptor instead.
func (*NotificationLifecycleEvent) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescGZIP(), []int{8}
}

func (x *NotificationLifecycleEvent) GetTenantContext() *v1.TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *NotificationLifecycleEvent) GetTraceContext() *v1.TraceContext {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

func (x *NotificationLifecycleEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NotificationLifecycleEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *NotificationLifecycleEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *NotificationLifecycleEvent) GetCausationEventId() string {
	if x != nil {
		return x.CausationEventId
	}
	return ""
}

func (x *NotificationLifecycleEvent) GetActorType() LifecycleActorType {
	if x != nil {
		return x.ActorType
	}
	return LifecycleActorType_LIFECYCLE_ACTOR_TYPE_UNSPECIFIED
}

func (x *NotificationLifecycleEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *NotificationLifecycleEvent) GetType() NotificationLifecycleEventType {
	if x != nil {
		return x.Type
	}
	return NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_UNSPECIFIED
}

func (x *NotificationLifecycleEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *NotificationLifecycleEvent) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NotificationLifecycleEvent) GetDetails() isNotificationLifecycleEvent_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *NotificationLifecycleEvent) GetAccepted() *AcceptedDetails {
	if x != nil {
		if x, ok := x.Details.(*NotificationLifecycleEvent_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *NotificationLifecycleEvent) GetDuplicate() *DuplicateDetails {
	if x != nil {
		if x, ok := x.Details.(*NotificationLifecycleEvent_Duplicate); ok {
			return x.Duplicate
		}
	}
	return nil
}

func (x *NotificationLifecycleEvent) GetRejected() *RejectedDetails {
	if x != nil {
		if x, ok := x.Details.(*NotificationLifecycleEvent_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *NotificationLifecycleEvent) GetSuppressed() *SuppressedDetails {
	if x != nil {
		if x, ok := x.Details.(*NotificationLifecycleEvent_Suppressed); ok {
			return x.Suppressed
		}
	}
	return nil
}

func (x *NotificationLifecycleEvent) GetRender() *RenderDetails {
	if x != nil {
		if x, ok := x.Details.(*NotificationLifecycleEvent_Render); ok {
			return x.Render
		}
	}
	return nil
}

func (x *NotificationLifecycleEvent) GetDelivery() *DeliveryDetails {
	if x != nil {
		if x, ok := x.Details.(*NotificationLifecycleEvent_Delivery); ok {
			return x.Delivery
		}
	}
	return nil
}

func (x *NotificationLifecycleEvent) GetDlq() *DlqDetails {
	if x != nil {
		if x, ok := x.Details.(*NotificationLifecycleEvent_Dlq); ok {
			return x.Dlq
		}
	}
	return nil
}

func (x *NotificationLifecycleEvent) GetReplay() *ReplayDetails {
	if x != nil {
		if x, ok := x.Details.(*NotificationLifecycleEvent_Replay); ok {
			return x.Replay
		}
	}
	return nil
}

type isNotificationLifecycleEvent_Details interface {
	isNotificationLifecycleEvent_Details()
}

type NotificationLifecycleEvent_Accepted struct {
	Accepted *AcceptedDetails `protobuf:"bytes,20,opt,name=accepted,proto3,oneof"`
}

type NotificationLifecycleEvent_Duplicate struct {
	Duplicate *DuplicateDetails `protobuf:"bytes,21,opt,name=duplicate,proto3,oneof"`
}

type NotificationLifecycleEvent_Rejected struct {
	Rejected *RejectedDetails `protobuf:"bytes,22,opt,name=rejected,proto3,oneof"`
}

type NotificationLifecycleEvent_Suppressed struct {
	Suppressed *SuppressedDetails `protobuf:"bytes,23,opt,name=suppressed,proto3,oneof"`
}

type NotificationLifecycleEvent_Render struct {
	Render *RenderDetails `protobuf:"bytes,24,opt,name=render,proto3,oneof"`
}

type NotificationLifecycleEvent_Delivery struct {
	Delivery *DeliveryDetails `protobuf:"bytes,25,opt,name=delivery,proto3,oneof"`
}

type NotificationLifecycleEvent_Dlq struct {
	Dlq *DlqDetails `protobuf:"bytes,26,opt,name=dlq,proto3,oneof"`
}

type NotificationLifecycleEvent_Replay struct {
	Replay *ReplayDetails `protobuf:"bytes,27,opt,name=replay,proto3,oneof"`
}

func (*NotificationLifecycleEvent_Accepted) isNotificationLifecycleEvent_Details() {}

func (*NotificationLifecycleEvent_Duplicate) isNotificationLifecycleEvent_Details() {}

func (*NotificationLifecycleEvent_Rejected) isNotificationLifecycleEvent_Details() {}

func (*NotificationLifecycleEvent_Suppressed) isNotificationLifecycleEvent_Details() {}

func (*NotificationLifecycleEvent_Render) isNotificationLifecycleEvent_Details() {}

func (*NotificationLifecycleEvent_Delivery) isNotificationLifecycleEvent_Details() {}

func (*NotificationLifecycleEvent_Dlq) isNotificationLifecycleEvent_Details() {}

func (*NotificationLifecycleEvent_Replay) isNotificationLifecycleEvent_Details() {}

var File_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDesc = "" +
	"\n" +
	"7sh/whoa/sutradhar/notification/v1/lifecycle_event.proto\x12!sh.whoa.sutradhar.notification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a1sh/whoa/sutradhar/common/v1/failure_context.proto\x1a*sh/whoa/sutradhar/common/v1/metadata.proto\x1a0sh/whoa/sutradhar/common/v1/tenant_context.proto\x1a/sh/whoa/sutradhar/common/v1/trace_context.proto\x1a:sh/whoa/sutradhar/notification/v1/notification_enums.proto\"\xb8\x01\n" +
	"\x0fAcceptedDetails\x12S\n" +
	"\bpriority\x18\x01 \x01(\x0e27.sh.whoa.sutradhar.notification.v1.NotificationPriorityR\bpriority\x12P\n" +
	"\achannel\x18\x02 \x01(\x0e26.sh.whoa.sutradhar.notification.v1.NotificationChannelR\achannel\"B\n" +
	"\x10DuplicateDetails\x12.\n" +
	"\x13existing_request_id\x18\x01 \x01(\tR\x11existingRequestId\"X\n" +
	"\x0fRejectedDetails\x12E\n" +
	"\afailure\x18\x01 \x01(\v2+.sh.whoa.sutradhar.common.v1.FailureContextR\afailure\"[\n" +
	"\x11SuppressedDetails\x12\x1f\n" +
	"\vreason_code\x18\x01 \x01(\tR\n" +
	"reasonCode\x12%\n" +
	"\x0ereason_message\x18\x02 \x01(\tR\rreasonMessage\"3\n" +
	"\rRenderDetails\x12\"\n" +
	"\rrender_job_id\x18\x01 \x01(\tR\vrenderJobId\"\xa0\x02\n" +
	"\x0fDeliveryDetails\x12(\n" +
	"\x10delivery_task_id\x18\x01 \x01(\tR\x0edeliveryTaskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12P\n" +
	"\achannel\x18\x03 \x01(\x0e26.sh.whoa.sutradhar.notification.v1.NotificationChannelR\achannel\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12&\n" +
	"\x0fprovider_sub_id\x18\x05 \x01(\tR\rproviderSubId\x12.\n" +
	"\x13provider_message_id\x18\x06 \x01(\tR\x11providerMessageId\"i\n" +
	"\n" +
	"DlqDetails\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12E\n" +
	"\afailure\x18\x02 \x01(\v2+.sh.whoa.sutradhar.common.v1.FailureContextR\afailure\"`\n" +
	"\rReplayDetails\x12*\n" +
	"\x11original_event_id\x18\x01 \x01(\tR\x0foriginalEventId\x12#\n" +
	"\rreplay_reason\x18\x02 \x01(\tR\freplayReason\"\xa1\n" +
	"\n" +
	"\x1aNotificationLifecycleEvent\x12Q\n" +
	"\x0etenant_context\x18\x01 \x01(\v2*.sh.whoa.sutradhar.common.v1.TenantContextR\rtenantContext\x12N\n" +
	"\rtrace_context\x18\x02 \x01(\v2).sh.whoa.sutradhar.common.v1.TraceContextR\ftraceContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12'\n" +
	"\x0fsequence_number\x18\x05 \x01(\x03R\x0esequenceNumber\x12,\n" +
	"\x12causation_event_id\x18\x06 \x01(\tR\x10causationEventId\x12T\n" +
	"\n" +
	"actor_type\x18\a \x01(\x0e25.sh.whoa.sutradhar.notification.v1.LifecycleActorTypeR\tactorType\x12\x19\n" +
	"\bactor_id\x18\b \x01(\tR\aactorId\x12U\n" +
	"\x04type\x18\t \x01(\x0e2A.sh.whoa.sutradhar.notification.v1.NotificationLifecycleEventTypeR\x04type\x12;\n" +
	"\voccurred_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12A\n" +
	"\bmetadata\x18\v \x01(\v2%.sh.whoa.sutradhar.common.v1.MetadataR\bmetadata\x12P\n" +
	"\baccepted\x18\x14 \x01(\v22.sh.whoa.sutradhar.notification.v1.AcceptedDetailsH\x00R\baccepted\x12S\n" +
	"\tduplicate\x18\x15 \x01(\v23.sh.whoa.sutradhar.notification.v1.DuplicateDetailsH\x00R\tduplicate\x12P\n" +
	"\brejected\x18\x16 \x01(\v22.sh.whoa.sutradhar.notification.v1.RejectedDetailsH\x00R\brejected\x12V\n" +
	"\n" +
	"suppressed\x18\x17 \x01(\v24.sh.whoa.sutradhar.notification.v1.SuppressedDetailsH\x00R\n" +
	"suppressed\x12J\n" +
	"\x06render\x18\x18 \x01(\v20.sh.whoa.sutradhar.notification.v1.RenderDetailsH\x00R\x06render\x12P\n" +
	"\bdelivery\x18\x19 \x01(\v22.sh.whoa.sutradhar.notification.v1.DeliveryDetailsH\x00R\bdelivery\x12A\n" +
	"\x03dlq\x18\x1a \x01(\v2-.sh.whoa.sutradhar.notification.v1.DlqDetailsH\x00R\x03dlq\x12J\n" +
	"\x06replay\x18\x1b \x01(\v20.sh.whoa.sutradhar.notification.v1.ReplayDetailsH\x00R\x06replayB\t\n" +
	"\adetailsB\xc0\x02\n" +
	"%com.sh.whoa.sutradhar.notification.v1B\x13LifecycleEventProtoP\x01ZYgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/notification/v1;notificationv1\xa2\x02\x04SWSN\xaa\x02!Sh.Whoa.Sutradhar.Notification.V1\xca\x02!Sh\\Whoa\\Sutradhar\\Notification\\V1\xe2\x02-Sh\\Whoa\\Sutradhar\\Notification\\V1\\GPBMetadata\xea\x02%Sh::Whoa::Sutradhar::Notification::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDesc), len(file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDescData
}

var file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_goTypes = []any{
	(*AcceptedDetails)(nil),             // 0: sh.whoa.sutradhar.notification.v1.AcceptedDetails
	(*DuplicateDetails)(nil),            // 1: sh.whoa.sutradhar.notification.v1.DuplicateDetails
	(*RejectedDetails)(nil),             // 2: sh.whoa.sutradhar.notification.v1.RejectedDetails
	(*SuppressedDetails)(nil),           // 3: sh.whoa.sutradhar.notification.v1.SuppressedDetails
	(*RenderDetails)(nil),               // 4: sh.whoa.sutradhar.notification.v1.RenderDetails
	(*DeliveryDetails)(nil),             // 5: sh.whoa.sutradhar.notification.v1.DeliveryDetails
	(*DlqDetails)(nil),                  // 6: sh.whoa.sutradhar.notification.v1.DlqDetails
	(*ReplayDetails)(nil),               // 7: sh.whoa.sutradhar.notification.v1.ReplayDetails
	(*NotificationLifecycleEvent)(nil),  // 8: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent
	(NotificationPriority)(0),           // 9: sh.whoa.sutradhar.notification.v1.NotificationPriority
	(NotificationChannel)(0),            // 10: sh.whoa.sutradhar.notification.v1.NotificationChannel
	(*v1.FailureContext)(nil),           // 11: sh.whoa.sutradhar.common.v1.FailureContext
	(*v1.TenantContext)(nil),            // 12: sh.whoa.sutradhar.common.v1.TenantContext
	(*v1.TraceContext)(nil),             // 13: sh.whoa.sutradhar.common.v1.TraceContext
	(LifecycleActorType)(0),             // 14: sh.whoa.sutradhar.notification.v1.LifecycleActorType
	(NotificationLifecycleEventType)(0), // 15: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEventType
	(*timestamppb.Timestamp)(nil),       // 16: google.protobuf.Timestamp
	(*v1.Metadata)(nil),                 // 17: sh.whoa.sutradhar.common.v1.Metadata
}
var file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_depIdxs = []int32{
	9,  // 0: sh.whoa.sutradhar.notification.v1.AcceptedDetails.priority:type_name -> sh.whoa.sutradhar.notification.v1.NotificationPriority
	10, // 1: sh.whoa.sutradhar.notification.v1.AcceptedDetails.channel:type_name -> sh.whoa.sutradhar.notification.v1.NotificationChannel
	11, // 2: sh.whoa.sutradhar.notification.v1.RejectedDetails.failure:type_name -> sh.whoa.sutradhar.common.v1.FailureContext
	10, // 3: sh.whoa.sutradhar.notification.v1.DeliveryDetails.channel:type_name -> sh.whoa.sutradhar.notification.v1.NotificationChannel
	11, // 4: sh.whoa.sutradhar.notification.v1.DlqDetails.failure:type_name -> sh.whoa.sutradhar.common.v1.FailureContext
	12, // 5: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.tenant_context:type_name -> sh.whoa.sutradhar.common.v1.TenantContext
	13, // 6: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.trace_context:type_name -> sh.whoa.sutradhar.common.v1.TraceContext
	14, // 7: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.actor_type:type_name -> sh.whoa.sutradhar.notification.v1.LifecycleActorType
	15, // 8: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.type:type_name -> sh.whoa.sutradhar.notification.v1.NotificationLifecycleEventType
	16, // 9: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.occurred_at:type_name -> google.protobuf.Timestamp
	17, // 10: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.metadata:type_name -> sh.whoa.sutradhar.common.v1.Metadata
	0,  // 11: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.accepted:type_name -> sh.whoa.sutradhar.notification.v1.AcceptedDetails
	1,  // 12: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.duplicate:type_name -> sh.whoa.sutradhar.notification.v1.DuplicateDetails
	2,  // 13: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.rejected:type_name -> sh.whoa.sutradhar.notification.v1.RejectedDetails
	3,  // 14: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.suppressed:type_name -> sh.whoa.sutradhar.notification.v1.SuppressedDetails
	4,  // 15: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.render:type_name -> sh.whoa.sutradhar.notification.v1.RenderDetails
	5,  // 16: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.delivery:type_name -> sh.whoa.sutradhar.notification.v1.DeliveryDetails
	6,  // 17: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.dlq:type_name -> sh.whoa.sutradhar.notification.v1.DlqDetails
	7,  // 18: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEvent.replay:type_name -> sh.whoa.sutradhar.notification.v1.ReplayDetails
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_init() }
func file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_init() {
	if File_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto != nil {
		return
	}
	file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_init()
	file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes[8].OneofWrappers = []any{
		(*NotificationLifecycleEvent_Accepted)(nil),
		(*NotificationLifecycleEvent_Duplicate)(nil),
		(*NotificationLifecycleEvent_Rejected)(nil),
		(*NotificationLifecycleEvent_Suppressed)(nil),
		(*NotificationLifecycleEvent_Render)(nil),
		(*NotificationLifecycleEvent_Delivery)(nil),
		(*NotificationLifecycleEvent_Dlq)(nil),
		(*NotificationLifecycleEvent_Replay)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDesc), len(file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto = out.File
	file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_goTypes = nil
	file_sh_whoa_sutradhar_notification_v1_lifecycle_event_proto_depIdxs = nil
}
