// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/notification/v1/notification_request.proto

package notificationv1

import (
	v1 "github.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TenantContext      *v1.TenantContext      `protobuf:"bytes,1,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	TraceContext       *v1.TraceContext       `protobuf:"bytes,2,opt,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty"`
	RequestId          string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SourceSystem       string                 `protobuf:"bytes,4,opt,name=source_system,json=sourceSystem,proto3" json:"source_system,omitempty"`
	SourceEventId      string                 `protobuf:"bytes,5,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	IdempotencyContext *v1.IdempotencyContext `protobuf:"bytes,6,opt,name=idempotency_context,json=idempotencyContext,proto3" json:"idempotency_context,omitempty"`
	Priority           NotificationPriority   `protobuf:"varint,7,opt,name=priority,proto3,enum=sh.whoa.sutradhar.notification.v1.NotificationPriority" json:"priority,omitempty"`
	Channel            NotificationChannel    `protobuf:"varint,8,opt,name=channel,proto3,enum=sh.whoa.sutradhar.notification.v1.NotificationChannel" json:"channel,omitempty"`
	RecipientRef       *RecipientRef          `protobuf:"bytes,9,opt,name=recipient_ref,json=recipientRef,proto3" json:"recipient_ref,omitempty"`
	Target             *NotificationTarget    `protobuf:"bytes,10,opt,name=target,proto3" json:"target,omitempty"`
	TemplateVariables  *v1.Metadata           `protobuf:"bytes,11,opt,name=template_variables,json=templateVariables,proto3" json:"template_variables,omitempty"`
	Metadata           *v1.Metadata           `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RequestedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_sh_whoa_sutradhar_notification_v1_notification_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_notification_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_notification_request_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationRequest) GetTenantContext() *v1.TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *NotificationRequest) GetTraceContext() *v1.TraceContext {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

func (x *NotificationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NotificationRequest) GetSourceSystem() string {
	if x != nil {
		return x.SourceSystem
	}
	return ""
}

func (x *NotificationRequest) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *NotificationRequest) GetIdempotencyContext() *v1.IdempotencyContext {
	if x != nil {
		return x.IdempotencyContext
	}
	return nil
}

func (x *NotificationRequest) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *NotificationRequest) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED
}

func (x *NotificationRequest) GetRecipientRef() *RecipientRef {
	if x != nil {
		return x.RecipientRef
	}
	return nil
}

func (x *NotificationRequest) GetTarget() *NotificationTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *NotificationRequest) GetTemplateVariables() *v1.Metadata {
	if x != nil {
		return x.TemplateVariables
	}
	return nil
}

func (x *NotificationRequest) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NotificationRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

var File_sh_whoa_sutradhar_notification_v1_notification_request_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_notification_v1_notification_request_proto_rawDesc = "" +
	"\n" +
	"<sh/whoa/sutradhar/notification/v1/notification_request.proto\x12!sh.whoa.sutradhar.notification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a5sh/whoa/sutradhar/common/v1/idempotency_context.proto\x1a*sh/whoa/sutradhar/common/v1/metadata.proto\x1a0sh/whoa/sutradhar/common/v1/tenant_context.proto\x1a/sh/whoa/sutradhar/common/v1/trace_context.proto\x1a:sh/whoa/sutradhar/notification/v1/notification_enums.proto\x1a;sh/whoa/sutradhar/notification/v1/notification_target.proto\x1a5sh/whoa/sutradhar/notification/v1/recipient_ref.proto\"\xaa\a\n" +
	"\x13NotificationRequest\x12Q\n" +
	"\x0etenant_context\x18\x01 \x01(\v2*.sh.whoa.sutradhar.common.v1.TenantContextR\rtenantContext\x12N\n" +
	"\rtrace_context\x18\x02 \x01(\v2).sh.whoa.sutradhar.common.v1.TraceContextR\ftraceContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12#\n" +
	"\rsource_system\x18\x04 \x01(\tR\fsourceSystem\x12&\n" +
	"\x0fsource_event_id\x18\x05 \x01(\tR\rsourceEventId\x12`\n" +
	"\x13idempotency_context\x18\x06 \x01(\v2/.sh.whoa.sutradhar.common.v1.IdempotencyContextR\x12idempotencyContext\x12S\n" +
	"\bpriority\x18\a \x01(\x0e27.sh.whoa.sutradhar.notification.v1.NotificationPriorityR\bpriority\x12P\n" +
	"\achannel\x18\b \x01(\x0e26.sh.whoa.sutradhar.notification.v1.NotificationChannelR\achannel\x12T\n" +
	"\rrecipient_ref\x18\t \x01(\v2/.sh.whoa.sutradhar.notification.v1.RecipientRefR\frecipientRef\x12M\n" +
	"\x06target\x18\n" +
	" \x01(\v25.sh.whoa.sutradhar.notification.v1.NotificationTargetR\x06target\x12T\n" +
	"\x12template_variables\x18\v \x01(\v2%.sh.whoa.sutradhar.common.v1.MetadataR\x11templateVariables\x12A\n" +
	"\bmetadata\x18\f \x01(\v2%.sh.whoa.sutradhar.common.v1.MetadataR\bmetadata\x12=\n" +
	"\frequested_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAtB\xc5\x02\n" +
	"%com.sh.whoa.sutradhar.notification.v1B\x18NotificationRequestProtoP\x01ZYgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/notification/v1;notificationv1\xa2\x02\x04SWSN\xaa\x02!Sh.Whoa.Sutradhar.Notification.V1\xca\x02!Sh\\Whoa\\Sutradhar\\Notification\\V1\xe2\x02-Sh\\Whoa\\Sutradhar\\Notification\\V1\\GPBMetadata\xea\x02%Sh::Whoa::Sutradhar::Notification::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_notification_v1_notification_request_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_notification_v1_notification_request_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_notification_v1_notification_request_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_notification_v1_notification_request_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_notification_v1_notification_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_notification_v1_notification_request_proto_rawDesc), len(file_sh_whoa_sutradhar_notification_v1_notification_request_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_notification_v1_notification_request_proto_rawDescData
}

var file_sh_whoa_sutradhar_notification_v1_notification_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sh_whoa_sutradhar_notification_v1_notification_request_proto_goTypes = []any{
	(*NotificationRequest)(nil),   // 0: sh.whoa.sutradhar.notification.v1.NotificationRequest
	(*v1.TenantContext)(nil),      // 1: sh.whoa.sutradhar.common.v1.TenantContext
	(*v1.TraceContext)(nil),       // 2: sh.whoa.sutradhar.common.v1.TraceContext
	(*v1.IdempotencyContext)(nil), // 3: sh.whoa.sutradhar.common.v1.IdempotencyContext
	(NotificationPriority)(0),     // 4: sh.whoa.sutradhar.notification.v1.NotificationPriority
	(NotificationChannel)(0),      // 5: sh.whoa.sutradhar.notification.v1.NotificationChannel
	(*RecipientRef)(nil),          // 6: sh.whoa.sutradhar.notification.v1.RecipientRef
	(*NotificationTarget)(nil),    // 7: sh.whoa.sutradhar.notification.v1.NotificationTarget
	(*v1.Metadata)(nil),           // 8: sh.whoa.sutradhar.common.v1.Metadata
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_sh_whoa_sutradhar_notification_v1_notification_request_proto_depIdxs = []int32{
	1,  // 0: sh.whoa.sutradhar.notification.v1.NotificationRequest.tenant_context:type_name -> sh.whoa.sutradhar.common.v1.TenantContext
	2,  // 1: sh.whoa.sutradhar.notification.v1.NotificationRequest.trace_context:type_name -> sh.whoa.sutradhar.common.v1.TraceContext
	3,  // 2: sh.whoa.sutradhar.notification.v1.NotificationRequest.idempotency_context:type_name -> sh.whoa.sutradhar.common.v1.IdempotencyContext
	4,  // 3: sh.whoa.sutradhar.notification.v1.NotificationRequest.priority:type_name -> sh.whoa.sutradhar.notification.v1.NotificationPriority
	5,  // 4: sh.whoa.sutradhar.notification.v1.NotificationRequest.channel:type_name -> sh.whoa.sutradhar.notification.v1.NotificationChannel
	6,  // 5: sh.whoa.sutradhar.notification.v1.NotificationRequest.recipient_ref:type_name -> sh.whoa.sutradhar.notification.v1.RecipientRef
	7,  // 6: sh.whoa.sutradhar.notification.v1.NotificationRequest.target:type_name -> sh.whoa.sutradhar.notification.v1.NotificationTarget
	8,  // 7: sh.whoa.sutradhar.notification.v1.NotificationRequest.template_variables:type_name -> sh.whoa.sutradhar.common.v1.Metadata
	8,  // 8: sh.whoa.sutradhar.notification.v1.NotificationRequest.metadata:type_name -> sh.whoa.sutradhar.common.v1.Metadata
	9,  // 9: sh.whoa.sutradhar.notification.v1.NotificationRequest.requested_at:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_notification_v1_notification_request_proto_init() }
func file_sh_whoa_sutradhar_notification_v1_notification_request_proto_init() {
	if File_sh_whoa_sutradhar_notification_v1_notification_request_proto != nil {
		return
	}
	file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_init()
	file_sh_whoa_sutradhar_notification_v1_notification_target_proto_init()
	file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_notification_v1_notification_request_proto_rawDesc), len(file_sh_whoa_sutradhar_notification_v1_notification_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_notification_v1_notification_request_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_notification_v1_notification_request_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_notification_v1_notification_request_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_notification_v1_notification_request_proto = out.File
	file_sh_whoa_sutradhar_notification_v1_notification_request_proto_goTypes = nil
	file_sh_whoa_sutradhar_notification_v1_notification_request_proto_depIdxs = nil
}
