// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/notification/v1/notification_enums.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationPriority int32

const (
	NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED NotificationPriority = 0
	NotificationPriority_NOTIFICATION_PRIORITY_CRITICAL    NotificationPriority = 1
	NotificationPriority_NOTIFICATION_PRIORITY_HIGH        NotificationPriority = 2
	NotificationPriority_NOTIFICATION_PRIORITY_NORMAL      NotificationPriority = 3
	NotificationPriority_NOTIFICATION_PRIORITY_LOW         NotificationPriority = 4
)

// Enum value maps for NotificationPriority.
var (
	NotificationPriority_name = map[int32]string{
		0: "NOTIFICATION_PRIORITY_UNSPECIFIED",
		1: "NOTIFICATION_PRIORITY_CRITICAL",
		2: "NOTIFICATION_PRIORITY_HIGH",
		3: "NOTIFICATION_PRIORITY_NORMAL",
		4: "NOTIFICATION_PRIORITY_LOW",
	}
	NotificationPriority_value = map[string]int32{
		"NOTIFICATION_PRIORITY_UNSPECIFIED": 0,
		"NOTIFICATION_PRIORITY_CRITICAL":    1,
		"NOTIFICATION_PRIORITY_HIGH":        2,
		"NOTIFICATION_PRIORITY_NORMAL":      3,
		"NOTIFICATION_PRIORITY_LOW":         4,
	}
)

func (x NotificationPriority) Enum() *NotificationPriority {
	p := new(NotificationPriority)
	*p = x
	return p
}

func (x NotificationPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes[0].Descriptor()
}

func (NotificationPriority) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes[0]
}

func (x NotificationPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationPriority.Descriptor instead.
func (NotificationPriority) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDescGZIP(), []int{0}
}

type NotificationChannel int32

const (
	NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED NotificationChannel = 0
	NotificationChannel_NOTIFICATION_CHANNEL_EMAIL       NotificationChannel = 1
	NotificationChannel_NOTIFICATION_CHANNEL_SMS         NotificationChannel = 2
	NotificationChannel_NOTIFICATION_CHANNEL_PUSH        NotificationChannel = 3
	NotificationChannel_NOTIFICATION_CHANNEL_WEBHOOK     NotificationChannel = 4
)

// Enum value maps for NotificationChannel.
var (
	NotificationChannel_name = map[int32]string{
		0: "NOTIFICATION_CHANNEL_UNSPECIFIED",
		1: "NOTIFICATION_CHANNEL_EMAIL",
		2: "NOTIFICATION_CHANNEL_SMS",
		3: "NOTIFICATION_CHANNEL_PUSH",
		4: "NOTIFICATION_CHANNEL_WEBHOOK",
	}
	NotificationChannel_value = map[string]int32{
		"NOTIFICATION_CHANNEL_UNSPECIFIED": 0,
		"NOTIFICATION_CHANNEL_EMAIL":       1,
		"NOTIFICATION_CHANNEL_SMS":         2,
		"NOTIFICATION_CHANNEL_PUSH":        3,
		"NOTIFICATION_CHANNEL_WEBHOOK":     4,
	}
)

func (x NotificationChannel) Enum() *NotificationChannel {
	p := new(NotificationChannel)
	*p = x
	return p
}

func (x NotificationChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes[1].Descriptor()
}

func (NotificationChannel) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes[1]
}

func (x NotificationChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationChannel.Descriptor instead.
func (NotificationChannel) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDescGZIP(), []int{1}
}

type PushPlatform int32

const (
	PushPlatform_PUSH_PLATFORM_UNSPECIFIED PushPlatform = 0
	PushPlatform_PUSH_PLATFORM_IOS         PushPlatform = 1
	PushPlatform_PUSH_PLATFORM_ANDROID     PushPlatform = 2
	PushPlatform_PUSH_PLATFORM_WEB         PushPlatform = 3
)

// Enum value maps for PushPlatform.
var (
	PushPlatform_name = map[int32]string{
		0: "PUSH_PLATFORM_UNSPECIFIED",
		1: "PUSH_PLATFORM_IOS",
		2: "PUSH_PLATFORM_ANDROID",
		3: "PUSH_PLATFORM_WEB",
	}
	PushPlatform_value = map[string]int32{
		"PUSH_PLATFORM_UNSPECIFIED": 0,
		"PUSH_PLATFORM_IOS":         1,
		"PUSH_PLATFORM_ANDROID":     2,
		"PUSH_PLATFORM_WEB":         3,
	}
)

func (x PushPlatform) Enum() *PushPlatform {
	p := new(PushPlatform)
	*p = x
	return p
}

func (x PushPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes[2].Descriptor()
}

func (PushPlatform) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes[2]
}

func (x PushPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushPlatform.Descriptor instead.
func (PushPlatform) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDescGZIP(), []int{2}
}

type NotificationLifecycleEventType int32

const (
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_UNSPECIFIED        NotificationLifecycleEventType = 0
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_ACCEPTED           NotificationLifecycleEventType = 1
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_DUPLICATE          NotificationLifecycleEventType = 2
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_REJECTED           NotificationLifecycleEventType = 3
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_SUPPRESSED         NotificationLifecycleEventType = 4
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_RENDER_REQUESTED   NotificationLifecycleEventType = 5
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_RENDER_SUCCEEDED   NotificationLifecycleEventType = 6
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_RENDER_FAILED      NotificationLifecycleEventType = 7
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_QUEUED    NotificationLifecycleEventType = 8
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_SENT      NotificationLifecycleEventType = 9
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_DELIVERED NotificationLifecycleEventType = 10
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_FAILED    NotificationLifecycleEventType = 11
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_CANCELLED          NotificationLifecycleEventType = 12
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_DLQ                NotificationLifecycleEventType = 13
	NotificationLifecycleEventType_NOTIFICATION_LIFECYCLE_EVENT_TYPE_REPLAYED           NotificationLifecycleEventType = 14
)

// Enum value maps for NotificationLifecycleEventType.
var (
	NotificationLifecycleEventType_name = map[int32]string{
		0:  "NOTIFICATION_LIFECYCLE_EVENT_TYPE_UNSPECIFIED",
		1:  "NOTIFICATION_LIFECYCLE_EVENT_TYPE_ACCEPTED",
		2:  "NOTIFICATION_LIFECYCLE_EVENT_TYPE_DUPLICATE",
		3:  "NOTIFICATION_LIFECYCLE_EVENT_TYPE_REJECTED",
		4:  "NOTIFICATION_LIFECYCLE_EVENT_TYPE_SUPPRESSED",
		5:  "NOTIFICATION_LIFECYCLE_EVENT_TYPE_RENDER_REQUESTED",
		6:  "NOTIFICATION_LIFECYCLE_EVENT_TYPE_RENDER_SUCCEEDED",
		7:  "NOTIFICATION_LIFECYCLE_EVENT_TYPE_RENDER_FAILED",
		8:  "NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_QUEUED",
		9:  "NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_SENT",
		10: "NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_DELIVERED",
		11: "NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_FAILED",
		12: "NOTIFICATION_LIFECYCLE_EVENT_TYPE_CANCELLED",
		13: "NOTIFICATION_LIFECYCLE_EVENT_TYPE_DLQ",
		14: "NOTIFICATION_LIFECYCLE_EVENT_TYPE_REPLAYED",
	}
	NotificationLifecycleEventType_value = map[string]int32{
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_UNSPECIFIED":        0,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_ACCEPTED":           1,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_DUPLICATE":          2,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_REJECTED":           3,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_SUPPRESSED":         4,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_RENDER_REQUESTED":   5,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_RENDER_SUCCEEDED":   6,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_RENDER_FAILED":      7,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_QUEUED":    8,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_SENT":      9,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_DELIVERED": 10,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_FAILED":    11,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_CANCELLED":          12,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_DLQ":                13,
		"NOTIFICATION_LIFECYCLE_EVENT_TYPE_REPLAYED":           14,
	}
)

func (x NotificationLifecycleEventType) Enum() *NotificationLifecycleEventType {
	p := new(NotificationLifecycleEventType)
	*p = x
	return p
}

func (x NotificationLifecycleEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationLifecycleEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes[3].Descriptor()
}

func (NotificationLifecycleEventType) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes[3]
}

func (x NotificationLifecycleEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationLifecycleEventType.Descriptor instead.
func (NotificationLifecycleEventType) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDescGZIP(), []int{3}
}

type LifecycleActorType int32

const (
	LifecycleActorType_LIFECYCLE_ACTOR_TYPE_UNSPECIFIED   LifecycleActorType = 0
	LifecycleActorType_LIFECYCLE_ACTOR_TYPE_SYSTEM        LifecycleActorType = 1
	LifecycleActorType_LIFECYCLE_ACTOR_TYPE_ADMIN_USER    LifecycleActorType = 2
	LifecycleActorType_LIFECYCLE_ACTOR_TYPE_SCHEDULED_JOB LifecycleActorType = 3
	LifecycleActorType_LIFECYCLE_ACTOR_TYPE_REPLAY_WORKER LifecycleActorType = 4
)

// Enum value maps for LifecycleActorType.
var (
	LifecycleActorType_name = map[int32]string{
		0: "LIFECYCLE_ACTOR_TYPE_UNSPECIFIED",
		1: "LIFECYCLE_ACTOR_TYPE_SYSTEM",
		2: "LIFECYCLE_ACTOR_TYPE_ADMIN_USER",
		3: "LIFECYCLE_ACTOR_TYPE_SCHEDULED_JOB",
		4: "LIFECYCLE_ACTOR_TYPE_REPLAY_WORKER",
	}
	LifecycleActorType_value = map[string]int32{
		"LIFECYCLE_ACTOR_TYPE_UNSPECIFIED":   0,
		"LIFECYCLE_ACTOR_TYPE_SYSTEM":        1,
		"LIFECYCLE_ACTOR_TYPE_ADMIN_USER":    2,
		"LIFECYCLE_ACTOR_TYPE_SCHEDULED_JOB": 3,
		"LIFECYCLE_ACTOR_TYPE_REPLAY_WORKER": 4,
	}
)

func (x LifecycleActorType) Enum() *LifecycleActorType {
	p := new(LifecycleActorType)
	*p = x
	return p
}

func (x LifecycleActorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleActorType) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes[4].Descriptor()
}

func (LifecycleActorType) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes[4]
}

func (x LifecycleActorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleActorType.Descriptor instead.
func (LifecycleActorType) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDescGZIP(), []int{4}
}

type NotificationTargetKind int32

const (
	NotificationTargetKind_NOTIFICATION_TARGET_KIND_UNSPECIFIED NotificationTargetKind = 0
	NotificationTargetKind_NOTIFICATION_TARGET_KIND_EMAIL       NotificationTargetKind = 1
	NotificationTargetKind_NOTIFICATION_TARGET_KIND_SMS         NotificationTargetKind = 2
	NotificationTargetKind_NOTIFICATION_TARGET_KIND_PUSH        NotificationTargetKind = 3
	NotificationTargetKind_NOTIFICATION_TARGET_KIND_WEBHOOK     NotificationTargetKind = 4
)

// Enum value maps for NotificationTargetKind.
var (
	NotificationTargetKind_name = map[int32]string{
		0: "NOTIFICATION_TARGET_KIND_UNSPECIFIED",
		1: "NOTIFICATION_TARGET_KIND_EMAIL",
		2: "NOTIFICATION_TARGET_KIND_SMS",
		3: "NOTIFICATION_TARGET_KIND_PUSH",
		4: "NOTIFICATION_TARGET_KIND_WEBHOOK",
	}
	NotificationTargetKind_value = map[string]int32{
		"NOTIFICATION_TARGET_KIND_UNSPECIFIED": 0,
		"NOTIFICATION_TARGET_KIND_EMAIL":       1,
		"NOTIFICATION_TARGET_KIND_SMS":         2,
		"NOTIFICATION_TARGET_KIND_PUSH":        3,
		"NOTIFICATION_TARGET_KIND_WEBHOOK":     4,
	}
)

func (x NotificationTargetKind) Enum() *NotificationTargetKind {
	p := new(NotificationTargetKind)
	*p = x
	return p
}

func (x NotificationTargetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationTargetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes[5].Descriptor()
}

func (NotificationTargetKind) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes[5]
}

func (x NotificationTargetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationTargetKind.Descriptor instead.
func (NotificationTargetKind) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDescGZIP(), []int{5}
}

var File_sh_whoa_sutradhar_notification_v1_notification_enums_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDesc = "" +
	"\n" +
	":sh/whoa/sutradhar/notification/v1/notification_enums.proto\x12!sh.whoa.sutradhar.notification.v1*\xc2\x01\n" +
	"\x14NotificationPriority\x12%\n" +
	"!NOTIFICATION_PRIORITY_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eNOTIFICATION_PRIORITY_CRITICAL\x10\x01\x12\x1e\n" +
	"\x1aNOTIFICATION_PRIORITY_HIGH\x10\x02\x12 \n" +
	"\x1cNOTIFICATION_PRIORITY_NORMAL\x10\x03\x12\x1d\n" +
	"\x19NOTIFICATION_PRIORITY_LOW\x10\x04*\xba\x01\n" +
	"\x13NotificationChannel\x12$\n" +
	" NOTIFICATION_CHANNEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNOTIFICATION_CHANNEL_EMAIL\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_CHANNEL_SMS\x10\x02\x12\x1d\n" +
	"\x19NOTIFICATION_CHANNEL_PUSH\x10\x03\x12 \n" +
	"\x1cNOTIFICATION_CHANNEL_WEBHOOK\x10\x04*v\n" +
	"\fPushPlatform\x12\x1d\n" +
	"\x19PUSH_PLATFORM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PUSH_PLATFORM_IOS\x10\x01\x12\x19\n" +
	"\x15PUSH_PLATFORM_ANDROID\x10\x02\x12\x15\n" +
	"\x11PUSH_PLATFORM_WEB\x10\x03*\xa4\x06\n" +
	"\x1eNotificationLifecycleEventType\x121\n" +
	"-NOTIFICATION_LIFECYCLE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12.\n" +
	"*NOTIFICATION_LIFECYCLE_EVENT_TYPE_ACCEPTED\x10\x01\x12/\n" +
	"+NOTIFICATION_LIFECYCLE_EVENT_TYPE_DUPLICATE\x10\x02\x12.\n" +
	"*NOTIFICATION_LIFECYCLE_EVENT_TYPE_REJECTED\x10\x03\x120\n" +
	",NOTIFICATION_LIFECYCLE_EVENT_TYPE_SUPPRESSED\x10\x04\x126\n" +
	"2NOTIFICATION_LIFECYCLE_EVENT_TYPE_RENDER_REQUESTED\x10\x05\x126\n" +
	"2NOTIFICATION_LIFECYCLE_EVENT_TYPE_RENDER_SUCCEEDED\x10\x06\x123\n" +
	"/NOTIFICATION_LIFECYCLE_EVENT_TYPE_RENDER_FAILED\x10\a\x125\n" +
	"1NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_QUEUED\x10\b\x123\n" +
	"/NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_SENT\x10\t\x128\n" +
	"4NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_DELIVERED\x10\n" +
	"\x125\n" +
	"1NOTIFICATION_LIFECYCLE_EVENT_TYPE_DELIVERY_FAILED\x10\v\x12/\n" +
	"+NOTIFICATION_LIFECYCLE_EVENT_TYPE_CANCELLED\x10\f\x12)\n" +
	"%NOTIFICATION_LIFECYCLE_EVENT_TYPE_DLQ\x10\r\x12.\n" +
	"*NOTIFICATION_LIFECYCLE_EVENT_TYPE_REPLAYED\x10\x0e*\xd0\x01\n" +
	"\x12LifecycleActorType\x12$\n" +
	" LIFECYCLE_ACTOR_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bLIFECYCLE_ACTOR_TYPE_SYSTEM\x10\x01\x12#\n" +
	"\x1fLIFECYCLE_ACTOR_TYPE_ADMIN_USER\x10\x02\x12&\n" +
	"\"LIFECYCLE_ACTOR_TYPE_SCHEDULED_JOB\x10\x03\x12&\n" +
	"\"LIFECYCLE_ACTOR_TYPE_REPLAY_WORKER\x10\x04*\xd1\x01\n" +
	"\x16NotificationTargetKind\x12(\n" +
	"$NOTIFICATION_TARGET_KIND_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eNOTIFICATION_TARGET_KIND_EMAIL\x10\x01\x12 \n" +
	"\x1cNOTIFICATION_TARGET_KIND_SMS\x10\x02\x12!\n" +
	"\x1dNOTIFICATION_TARGET_KIND_PUSH\x10\x03\x12$\n" +
	" NOTIFICATION_TARGET_KIND_WEBHOOK\x10\x04B\xc3\x02\n" +
	"%com.sh.whoa.sutradhar.notification.v1B\x16NotificationEnumsProtoP\x01ZYgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/notification/v1;notificationv1\xa2\x02\x04SWSN\xaa\x02!Sh.Whoa.Sutradhar.Notification.V1\xca\x02!Sh\\Whoa\\Sutradhar\\Notification\\V1\xe2\x02-Sh\\Whoa\\Sutradhar\\Notification\\V1\\GPBMetadata\xea\x02%Sh::Whoa::Sutradhar::Notification::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDesc), len(file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDescData
}

var file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_goTypes = []any{
	(NotificationPriority)(0),           // 0: sh.whoa.sutradhar.notification.v1.NotificationPriority
	(NotificationChannel)(0),            // 1: sh.whoa.sutradhar.notification.v1.NotificationChannel
	(PushPlatform)(0),                   // 2: sh.whoa.sutradhar.notification.v1.PushPlatform
	(NotificationLifecycleEventType)(0), // 3: sh.whoa.sutradhar.notification.v1.NotificationLifecycleEventType
	(LifecycleActorType)(0),             // 4: sh.whoa.sutradhar.notification.v1.LifecycleActorType
	(NotificationTargetKind)(0),         // 5: sh.whoa.sutradhar.notification.v1.NotificationTargetKind
}
var file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_init() }
func file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_init() {
	if File_sh_whoa_sutradhar_notification_v1_notification_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDesc), len(file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_depIdxs,
		EnumInfos:         file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_enumTypes,
	}.Build()
	File_sh_whoa_sutradhar_notification_v1_notification_enums_proto = out.File
	file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_goTypes = nil
	file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_depIdxs = nil
}
