// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/notification/v1/notification_target.proto

package notificationv1

import (
	v1 "github.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailAddress  string                 `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailTarget) Reset() {
	*x = EmailTarget{}
	mi := &file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTarget) ProtoMessage() {}

func (x *EmailTarget) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTarget.ProtoReflect.Descriptor instead.
func (*EmailTarget) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDescGZIP(), []int{0}
}

func (x *EmailTarget) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *EmailTarget) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type SmsTarget struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumberE164 string                 `protobuf:"bytes,1,opt,name=phone_number_e164,json=phoneNumberE164,proto3" json:"phone_number_e164,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SmsTarget) Reset() {
	*x = SmsTarget{}
	mi := &file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsTarget) ProtoMessage() {}

func (x *SmsTarget) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsTarget.ProtoReflect.Descriptor instead.
func (*SmsTarget) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDescGZIP(), []int{1}
}

func (x *SmsTarget) GetPhoneNumberE164() string {
	if x != nil {
		return x.PhoneNumberE164
	}
	return ""
}

type PushTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Destination:
	//
	//	*PushTarget_DeviceRef
	//	*PushTarget_DeviceToken
	Destination   isPushTarget_Destination `protobuf_oneof:"destination"`
	Platform      PushPlatform             `protobuf:"varint,3,opt,name=platform,proto3,enum=sh.whoa.sutradhar.notification.v1.PushPlatform" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushTarget) Reset() {
	*x = PushTarget{}
	mi := &file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTarget) ProtoMessage() {}

func (x *PushTarget) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTarget.ProtoReflect.Descriptor instead.
func (*PushTarget) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDescGZIP(), []int{2}
}

func (x *PushTarget) GetDestination() isPushTarget_Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *PushTarget) GetDeviceRef() string {
	if x != nil {
		if x, ok := x.Destination.(*PushTarget_DeviceRef); ok {
			return x.DeviceRef
		}
	}
	return ""
}

func (x *PushTarget) GetDeviceToken() string {
	if x != nil {
		if x, ok := x.Destination.(*PushTarget_DeviceToken); ok {
			return x.DeviceToken
		}
	}
	return ""
}

func (x *PushTarget) GetPlatform() PushPlatform {
	if x != nil {
		return x.Platform
	}
	return PushPlatform_PUSH_PLATFORM_UNSPECIFIED
}

type isPushTarget_Destination interface {
	isPushTarget_Destination()
}

type PushTarget_DeviceRef struct {
	DeviceRef string `protobuf:"bytes,1,opt,name=device_ref,json=deviceRef,proto3,oneof"`
}

type PushTarget_DeviceToken struct {
	DeviceToken string `protobuf:"bytes,2,opt,name=device_token,json=deviceToken,proto3,oneof"`
}

func (*PushTarget_DeviceRef) isPushTarget_Destination() {}

func (*PushTarget_DeviceToken) isPushTarget_Destination() {}

type WebhookTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Destination:
	//
	//	*WebhookTarget_EndpointRef
	//	*WebhookTarget_Url
	Destination   isWebhookTarget_Destination `protobuf_oneof:"destination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookTarget) Reset() {
	*x = WebhookTarget{}
	mi := &file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookTarget) ProtoMessage() {}

func (x *WebhookTarget) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookTarget.ProtoReflect.Descriptor instead.
func (*WebhookTarget) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDescGZIP(), []int{3}
}

func (x *WebhookTarget) GetDestination() isWebhookTarget_Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *WebhookTarget) GetEndpointRef() string {
	if x != nil {
		if x, ok := x.Destination.(*WebhookTarget_EndpointRef); ok {
			return x.EndpointRef
		}
	}
	return ""
}

func (x *WebhookTarget) GetUrl() string {
	if x != nil {
		if x, ok := x.Destination.(*WebhookTarget_Url); ok {
			return x.Url
		}
	}
	return ""
}

type isWebhookTarget_Destination interface {
	isWebhookTarget_Destination()
}

type WebhookTarget_EndpointRef struct {
	EndpointRef string `protobuf:"bytes,1,opt,name=endpoint_ref,json=endpointRef,proto3,oneof"`
}

type WebhookTarget_Url struct {
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

func (*WebhookTarget_EndpointRef) isWebhookTarget_Destination() {}

func (*WebhookTarget_Url) isWebhookTarget_Destination() {}

type NotificationTarget struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Kind        NotificationTargetKind `protobuf:"varint,1,opt,name=kind,proto3,enum=sh.whoa.sutradhar.notification.v1.NotificationTargetKind" json:"kind,omitempty"`
	Sensitivity v1.SensitivityClass    `protobuf:"varint,2,opt,name=sensitivity,proto3,enum=sh.whoa.sutradhar.common.v1.SensitivityClass" json:"sensitivity,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*NotificationTarget_Email
	//	*NotificationTarget_Sms
	//	*NotificationTarget_Push
	//	*NotificationTarget_Webhook
	Target        isNotificationTarget_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationTarget) Reset() {
	*x = NotificationTarget{}
	mi := &file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationTarget) ProtoMessage() {}

func (x *NotificationTarget) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationTarget.ProtoReflect.Descriptor instead.
func (*NotificationTarget) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDescGZIP(), []int{4}
}

func (x *NotificationTarget) GetKind() NotificationTargetKind {
	if x != nil {
		return x.Kind
	}
	return NotificationTargetKind_NOTIFICATION_TARGET_KIND_UNSPECIFIED
}

func (x *NotificationTarget) GetSensitivity() v1.SensitivityClass {
	if x != nil {
		return x.Sensitivity
	}
	return v1.SensitivityClass(0)
}

func (x *NotificationTarget) GetTarget() isNotificationTarget_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *NotificationTarget) GetEmail() *EmailTarget {
	if x != nil {
		if x, ok := x.Target.(*NotificationTarget_Email); ok {
			return x.Email
		}
	}
	return nil
}

func (x *NotificationTarget) GetSms() *SmsTarget {
	if x != nil {
		if x, ok := x.Target.(*NotificationTarget_Sms); ok {
			return x.Sms
		}
	}
	return nil
}

func (x *NotificationTarget) GetPush() *PushTarget {
	if x != nil {
		if x, ok := x.Target.(*NotificationTarget_Push); ok {
			return x.Push
		}
	}
	return nil
}

func (x *NotificationTarget) GetWebhook() *WebhookTarget {
	if x != nil {
		if x, ok := x.Target.(*NotificationTarget_Webhook); ok {
			return x.Webhook
		}
	}
	return nil
}

type isNotificationTarget_Target interface {
	isNotificationTarget_Target()
}

type NotificationTarget_Email struct {
	Email *EmailTarget `protobuf:"bytes,10,opt,name=email,proto3,oneof"`
}

type NotificationTarget_Sms struct {
	Sms *SmsTarget `protobuf:"bytes,11,opt,name=sms,proto3,oneof"`
}

type NotificationTarget_Push struct {
	Push *PushTarget `protobuf:"bytes,12,opt,name=push,proto3,oneof"`
}

type NotificationTarget_Webhook struct {
	Webhook *WebhookTarget `protobuf:"bytes,13,opt,name=webhook,proto3,oneof"`
}

func (*NotificationTarget_Email) isNotificationTarget_Target() {}

func (*NotificationTarget_Sms) isNotificationTarget_Target() {}

func (*NotificationTarget_Push) isNotificationTarget_Target() {}

func (*NotificationTarget_Webhook) isNotificationTarget_Target() {}

var File_sh_whoa_sutradhar_notification_v1_notification_target_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDesc = "" +
	"\n" +
	";sh/whoa/sutradhar/notification/v1/notification_target.proto\x12!sh.whoa.sutradhar.notification.v1\x1a.sh/whoa/sutradhar/common/v1/common_enums.proto\x1a:sh/whoa/sutradhar/notification/v1/notification_enums.proto\"U\n" +
	"\vEmailTarget\x12#\n" +
	"\remail_address\x18\x01 \x01(\tR\femailAddress\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"7\n" +
	"\tSmsTarget\x12*\n" +
	"\x11phone_number_e164\x18\x01 \x01(\tR\x0fphoneNumberE164\"\xae\x01\n" +
	"\n" +
	"PushTarget\x12\x1f\n" +
	"\n" +
	"device_ref\x18\x01 \x01(\tH\x00R\tdeviceRef\x12#\n" +
	"\fdevice_token\x18\x02 \x01(\tH\x00R\vdeviceToken\x12K\n" +
	"\bplatform\x18\x03 \x01(\x0e2/.sh.whoa.sutradhar.notification.v1.PushPlatformR\bplatformB\r\n" +
	"\vdestination\"W\n" +
	"\rWebhookTarget\x12#\n" +
	"\fendpoint_ref\x18\x01 \x01(\tH\x00R\vendpointRef\x12\x12\n" +
	"\x03url\x18\x02 \x01(\tH\x00R\x03urlB\r\n" +
	"\vdestination\"\xdb\x03\n" +
	"\x12NotificationTarget\x12M\n" +
	"\x04kind\x18\x01 \x01(\x0e29.sh.whoa.sutradhar.notification.v1.NotificationTargetKindR\x04kind\x12O\n" +
	"\vsensitivity\x18\x02 \x01(\x0e2-.sh.whoa.sutradhar.common.v1.SensitivityClassR\vsensitivity\x12F\n" +
	"\x05email\x18\n" +
	" \x01(\v2..sh.whoa.sutradhar.notification.v1.EmailTargetH\x00R\x05email\x12@\n" +
	"\x03sms\x18\v \x01(\v2,.sh.whoa.sutradhar.notification.v1.SmsTargetH\x00R\x03sms\x12C\n" +
	"\x04push\x18\f \x01(\v2-.sh.whoa.sutradhar.notification.v1.PushTargetH\x00R\x04push\x12L\n" +
	"\awebhook\x18\r \x01(\v20.sh.whoa.sutradhar.notification.v1.WebhookTargetH\x00R\awebhookB\b\n" +
	"\x06targetB\xc4\x02\n" +
	"%com.sh.whoa.sutradhar.notification.v1B\x17NotificationTargetProtoP\x01ZYgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/notification/v1;notificationv1\xa2\x02\x04SWSN\xaa\x02!Sh.Whoa.Sutradhar.Notification.V1\xca\x02!Sh\\Whoa\\Sutradhar\\Notification\\V1\xe2\x02-Sh\\Whoa\\Sutradhar\\Notification\\V1\\GPBMetadata\xea\x02%Sh::Whoa::Sutradhar::Notification::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDesc), len(file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDescData
}

var file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sh_whoa_sutradhar_notification_v1_notification_target_proto_goTypes = []any{
	(*EmailTarget)(nil),         // 0: sh.whoa.sutradhar.notification.v1.EmailTarget
	(*SmsTarget)(nil),           // 1: sh.whoa.sutradhar.notification.v1.SmsTarget
	(*PushTarget)(nil),          // 2: sh.whoa.sutradhar.notification.v1.PushTarget
	(*WebhookTarget)(nil),       // 3: sh.whoa.sutradhar.notification.v1.WebhookTarget
	(*NotificationTarget)(nil),  // 4: sh.whoa.sutradhar.notification.v1.NotificationTarget
	(PushPlatform)(0),           // 5: sh.whoa.sutradhar.notification.v1.PushPlatform
	(NotificationTargetKind)(0), // 6: sh.whoa.sutradhar.notification.v1.NotificationTargetKind
	(v1.SensitivityClass)(0),    // 7: sh.whoa.sutradhar.common.v1.SensitivityClass
}
var file_sh_whoa_sutradhar_notification_v1_notification_target_proto_depIdxs = []int32{
	5, // 0: sh.whoa.sutradhar.notification.v1.PushTarget.platform:type_name -> sh.whoa.sutradhar.notification.v1.PushPlatform
	6, // 1: sh.whoa.sutradhar.notification.v1.NotificationTarget.kind:type_name -> sh.whoa.sutradhar.notification.v1.NotificationTargetKind
	7, // 2: sh.whoa.sutradhar.notification.v1.NotificationTarget.sensitivity:type_name -> sh.whoa.sutradhar.common.v1.SensitivityClass
	0, // 3: sh.whoa.sutradhar.notification.v1.NotificationTarget.email:type_name -> sh.whoa.sutradhar.notification.v1.EmailTarget
	1, // 4: sh.whoa.sutradhar.notification.v1.NotificationTarget.sms:type_name -> sh.whoa.sutradhar.notification.v1.SmsTarget
	2, // 5: sh.whoa.sutradhar.notification.v1.NotificationTarget.push:type_name -> sh.whoa.sutradhar.notification.v1.PushTarget
	3, // 6: sh.whoa.sutradhar.notification.v1.NotificationTarget.webhook:type_name -> sh.whoa.sutradhar.notification.v1.WebhookTarget
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_notification_v1_notification_target_proto_init() }
func file_sh_whoa_sutradhar_notification_v1_notification_target_proto_init() {
	if File_sh_whoa_sutradhar_notification_v1_notification_target_proto != nil {
		return
	}
	file_sh_whoa_sutradhar_notification_v1_notification_enums_proto_init()
	file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[2].OneofWrappers = []any{
		(*PushTarget_DeviceRef)(nil),
		(*PushTarget_DeviceToken)(nil),
	}
	file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[3].OneofWrappers = []any{
		(*WebhookTarget_EndpointRef)(nil),
		(*WebhookTarget_Url)(nil),
	}
	file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes[4].OneofWrappers = []any{
		(*NotificationTarget_Email)(nil),
		(*NotificationTarget_Sms)(nil),
		(*NotificationTarget_Push)(nil),
		(*NotificationTarget_Webhook)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDesc), len(file_sh_whoa_sutradhar_notification_v1_notification_target_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_notification_v1_notification_target_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_notification_v1_notification_target_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_notification_v1_notification_target_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_notification_v1_notification_target_proto = out.File
	file_sh_whoa_sutradhar_notification_v1_notification_target_proto_goTypes = nil
	file_sh_whoa_sutradhar_notification_v1_notification_target_proto_depIdxs = nil
}
