// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/notification/v1/recipient_ref.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecipientRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipientRef) Reset() {
	*x = RecipientRef{}
	mi := &file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipientRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipientRef) ProtoMessage() {}

func (x *RecipientRef) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipientRef.ProtoReflect.Descriptor instead.
func (*RecipientRef) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_rawDescGZIP(), []int{0}
}

func (x *RecipientRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RecipientRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RecipientRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_sh_whoa_sutradhar_notification_v1_recipient_ref_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_rawDesc = "" +
	"\n" +
	"5sh/whoa/sutradhar/notification/v1/recipient_ref.proto\x12!sh.whoa.sutradhar.notification.v1\"P\n" +
	"\fRecipientRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02idB\xbe\x02\n" +
	"%com.sh.whoa.sutradhar.notification.v1B\x11RecipientRefProtoP\x01ZYgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/notification/v1;notificationv1\xa2\x02\x04SWSN\xaa\x02!Sh.Whoa.Sutradhar.Notification.V1\xca\x02!Sh\\Whoa\\Sutradhar\\Notification\\V1\xe2\x02-Sh\\Whoa\\Sutradhar\\Notification\\V1\\GPBMetadata\xea\x02%Sh::Whoa::Sutradhar::Notification::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_rawDesc), len(file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_rawDescData
}

var file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_goTypes = []any{
	(*RecipientRef)(nil), // 0: sh.whoa.sutradhar.notification.v1.RecipientRef
}
var file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_init() }
func file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_init() {
	if File_sh_whoa_sutradhar_notification_v1_recipient_ref_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_rawDesc), len(file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_notification_v1_recipient_ref_proto = out.File
	file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_goTypes = nil
	file_sh_whoa_sutradhar_notification_v1_recipient_ref_proto_depIdxs = nil
}
