// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/template/v1/template_ref.proto

package templatev1

import (
	v1 "github.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/notification/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LatestActiveTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	MaxAgeSeconds *int64                 `protobuf:"varint,2,opt,name=max_age_seconds,json=maxAgeSeconds,proto3,oneof" json:"max_age_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestActiveTemplate) Reset() {
	*x = LatestActiveTemplate{}
	mi := &file_sh_whoa_sutradhar_template_v1_template_ref_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestActiveTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestActiveTemplate) ProtoMessage() {}

func (x *LatestActiveTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_template_v1_template_ref_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestActiveTemplate.ProtoReflect.Descriptor instead.
func (*LatestActiveTemplate) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDescGZIP(), []int{0}
}

func (x *LatestActiveTemplate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LatestActiveTemplate) GetMaxAgeSeconds() int64 {
	if x != nil && x.MaxAgeSeconds != nil {
		return *x.MaxAgeSeconds
	}
	return 0
}

type TemplateRef struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TemplateKey string                 `protobuf:"bytes,1,opt,name=template_key,json=templateKey,proto3" json:"template_key,omitempty"`
	Locale      string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	Channel     v1.NotificationChannel `protobuf:"varint,3,opt,name=channel,proto3,enum=sh.whoa.sutradhar.notification.v1.NotificationChannel" json:"channel,omitempty"`
	Variant     string                 `protobuf:"bytes,4,opt,name=variant,proto3" json:"variant,omitempty"`
	// Types that are valid to be assigned to VersionSelector:
	//
	//	*TemplateRef_Version
	//	*TemplateRef_LatestActive
	VersionSelector isTemplateRef_VersionSelector `protobuf_oneof:"version_selector"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TemplateRef) Reset() {
	*x = TemplateRef{}
	mi := &file_sh_whoa_sutradhar_template_v1_template_ref_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateRef) ProtoMessage() {}

func (x *TemplateRef) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_template_v1_template_ref_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateRef.ProtoReflect.Descriptor instead.
func (*TemplateRef) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDescGZIP(), []int{1}
}

func (x *TemplateRef) GetTemplateKey() string {
	if x != nil {
		return x.TemplateKey
	}
	return ""
}

func (x *TemplateRef) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *TemplateRef) GetChannel() v1.NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return v1.NotificationChannel(0)
}

func (x *TemplateRef) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *TemplateRef) GetVersionSelector() isTemplateRef_VersionSelector {
	if x != nil {
		return x.VersionSelector
	}
	return nil
}

func (x *TemplateRef) GetVersion() string {
	if x != nil {
		if x, ok := x.VersionSelector.(*TemplateRef_Version); ok {
			return x.Version
		}
	}
	return ""
}

func (x *TemplateRef) GetLatestActive() *LatestActiveTemplate {
	if x != nil {
		if x, ok := x.VersionSelector.(*TemplateRef_LatestActive); ok {
			return x.LatestActive
		}
	}
	return nil
}

type isTemplateRef_VersionSelector interface {
	isTemplateRef_VersionSelector()
}

type TemplateRef_Version struct {
	Version string `protobuf:"bytes,5,opt,name=version,proto3,oneof"`
}

type TemplateRef_LatestActive struct {
	LatestActive *LatestActiveTemplate `protobuf:"bytes,6,opt,name=latest_active,json=latestActive,proto3,oneof"`
}

func (*TemplateRef_Version) isTemplateRef_VersionSelector() {}

func (*TemplateRef_LatestActive) isTemplateRef_VersionSelector() {}

var File_sh_whoa_sutradhar_template_v1_template_ref_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDesc = "" +
	"\n" +
	"0sh/whoa/sutradhar/template/v1/template_ref.proto\x12\x1dsh.whoa.sutradhar.template.v1\x1a:sh/whoa/sutradhar/notification/v1/notification_enums.proto\"o\n" +
	"\x14LatestActiveTemplate\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12+\n" +
	"\x0fmax_age_seconds\x18\x02 \x01(\x03H\x00R\rmaxAgeSeconds\x88\x01\x01B\x12\n" +
	"\x10_max_age_seconds\"\xc0\x02\n" +
	"\vTemplateRef\x12!\n" +
	"\ftemplate_key\x18\x01 \x01(\tR\vtemplateKey\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\x12P\n" +
	"\achannel\x18\x03 \x01(\x0e26.sh.whoa.sutradhar.notification.v1.NotificationChannelR\achannel\x12\x18\n" +
	"\avariant\x18\x04 \x01(\tR\avariant\x12\x1a\n" +
	"\aversion\x18\x05 \x01(\tH\x00R\aversion\x12Z\n" +
	"\rlatest_active\x18\x06 \x01(\v23.sh.whoa.sutradhar.template.v1.LatestActiveTemplateH\x00R\flatestActiveB\x12\n" +
	"\x10version_selectorB\xa1\x02\n" +
	"!com.sh.whoa.sutradhar.template.v1B\x10TemplateRefProtoP\x01ZQgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/template/v1;templatev1\xa2\x02\x04SWST\xaa\x02\x1dSh.Whoa.Sutradhar.Template.V1\xca\x02\x1dSh\\Whoa\\Sutradhar\\Template\\V1\xe2\x02)Sh\\Whoa\\Sutradhar\\Template\\V1\\GPBMetadata\xea\x02!Sh::Whoa::Sutradhar::Template::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDesc), len(file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDescData
}

var file_sh_whoa_sutradhar_template_v1_template_ref_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sh_whoa_sutradhar_template_v1_template_ref_proto_goTypes = []any{
	(*LatestActiveTemplate)(nil), // 0: sh.whoa.sutradhar.template.v1.LatestActiveTemplate
	(*TemplateRef)(nil),          // 1: sh.whoa.sutradhar.template.v1.TemplateRef
	(v1.NotificationChannel)(0),  // 2: sh.whoa.sutradhar.notification.v1.NotificationChannel
}
var file_sh_whoa_sutradhar_template_v1_template_ref_proto_depIdxs = []int32{
	2, // 0: sh.whoa.sutradhar.template.v1.TemplateRef.channel:type_name -> sh.whoa.sutradhar.notification.v1.NotificationChannel
	0, // 1: sh.whoa.sutradhar.template.v1.TemplateRef.latest_active:type_name -> sh.whoa.sutradhar.template.v1.LatestActiveTemplate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_template_v1_template_ref_proto_init() }
func file_sh_whoa_sutradhar_template_v1_template_ref_proto_init() {
	if File_sh_whoa_sutradhar_template_v1_template_ref_proto != nil {
		return
	}
	file_sh_whoa_sutradhar_template_v1_template_ref_proto_msgTypes[0].OneofWrappers = []any{}
	file_sh_whoa_sutradhar_template_v1_template_ref_proto_msgTypes[1].OneofWrappers = []any{
		(*TemplateRef_Version)(nil),
		(*TemplateRef_LatestActive)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDesc), len(file_sh_whoa_sutradhar_template_v1_template_ref_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_template_v1_template_ref_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_template_v1_template_ref_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_template_v1_template_ref_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_template_v1_template_ref_proto = out.File
	file_sh_whoa_sutradhar_template_v1_template_ref_proto_goTypes = nil
	file_sh_whoa_sutradhar_template_v1_template_ref_proto_depIdxs = nil
}
