// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/template/v1/template_enums.proto

package templatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderStatus int32

const (
	RenderStatus_RENDER_STATUS_UNSPECIFIED      RenderStatus = 0
	RenderStatus_RENDER_STATUS_SUCCEEDED        RenderStatus = 1
	RenderStatus_RENDER_STATUS_FAILED_RETRYABLE RenderStatus = 2
	RenderStatus_RENDER_STATUS_FAILED_FINAL     RenderStatus = 3
)

// Enum value maps for RenderStatus.
var (
	RenderStatus_name = map[int32]string{
		0: "RENDER_STATUS_UNSPECIFIED",
		1: "RENDER_STATUS_SUCCEEDED",
		2: "RENDER_STATUS_FAILED_RETRYABLE",
		3: "RENDER_STATUS_FAILED_FINAL",
	}
	RenderStatus_value = map[string]int32{
		"RENDER_STATUS_UNSPECIFIED":      0,
		"RENDER_STATUS_SUCCEEDED":        1,
		"RENDER_STATUS_FAILED_RETRYABLE": 2,
		"RENDER_STATUS_FAILED_FINAL":     3,
	}
)

func (x RenderStatus) Enum() *RenderStatus {
	p := new(RenderStatus)
	*p = x
	return p
}

func (x RenderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RenderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_template_v1_template_enums_proto_enumTypes[0].Descriptor()
}

func (RenderStatus) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_template_v1_template_enums_proto_enumTypes[0]
}

func (x RenderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RenderStatus.Descriptor instead.
func (RenderStatus) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_template_v1_template_enums_proto_rawDescGZIP(), []int{0}
}

var File_sh_whoa_sutradhar_template_v1_template_enums_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_template_v1_template_enums_proto_rawDesc = "" +
	"\n" +
	"2sh/whoa/sutradhar/template/v1/template_enums.proto\x12\x1dsh.whoa.sutradhar.template.v1*\x8e\x01\n" +
	"\fRenderStatus\x12\x1d\n" +
	"\x19RENDER_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RENDER_STATUS_SUCCEEDED\x10\x01\x12\"\n" +
	"\x1eRENDER_STATUS_FAILED_RETRYABLE\x10\x02\x12\x1e\n" +
	"\x1aRENDER_STATUS_FAILED_FINAL\x10\x03B\xa3\x02\n" +
	"!com.sh.whoa.sutradhar.template.v1B\x12TemplateEnumsProtoP\x01ZQgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/template/v1;templatev1\xa2\x02\x04SWST\xaa\x02\x1dSh.Whoa.Sutradhar.Template.V1\xca\x02\x1dSh\\Whoa\\Sutradhar\\Template\\V1\xe2\x02)Sh\\Whoa\\Sutradhar\\Template\\V1\\GPBMetadata\xea\x02!Sh::Whoa::Sutradhar::Template::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_template_v1_template_enums_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_template_v1_template_enums_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_template_v1_template_enums_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_template_v1_template_enums_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_template_v1_template_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_template_v1_template_enums_proto_rawDesc), len(file_sh_whoa_sutradhar_template_v1_template_enums_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_template_v1_template_enums_proto_rawDescData
}

var file_sh_whoa_sutradhar_template_v1_template_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sh_whoa_sutradhar_template_v1_template_enums_proto_goTypes = []any{
	(RenderStatus)(0), // 0: sh.whoa.sutradhar.template.v1.RenderStatus
}
var file_sh_whoa_sutradhar_template_v1_template_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_template_v1_template_enums_proto_init() }
func file_sh_whoa_sutradhar_template_v1_template_enums_proto_init() {
	if File_sh_whoa_sutradhar_template_v1_template_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_template_v1_template_enums_proto_rawDesc), len(file_sh_whoa_sutradhar_template_v1_template_enums_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_template_v1_template_enums_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_template_v1_template_enums_proto_depIdxs,
		EnumInfos:         file_sh_whoa_sutradhar_template_v1_template_enums_proto_enumTypes,
	}.Build()
	File_sh_whoa_sutradhar_template_v1_template_enums_proto = out.File
	file_sh_whoa_sutradhar_template_v1_template_enums_proto_goTypes = nil
	file_sh_whoa_sutradhar_template_v1_template_enums_proto_depIdxs = nil
}
