// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/preference/v1/preference_enums.proto

package preferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreferenceState int32

const (
	PreferenceState_PREFERENCE_STATE_UNSPECIFIED PreferenceState = 0
	PreferenceState_PREFERENCE_STATE_ALLOWED     PreferenceState = 1
	PreferenceState_PREFERENCE_STATE_SUPPRESSED  PreferenceState = 2
)

// Enum value maps for PreferenceState.
var (
	PreferenceState_name = map[int32]string{
		0: "PREFERENCE_STATE_UNSPECIFIED",
		1: "PREFERENCE_STATE_ALLOWED",
		2: "PREFERENCE_STATE_SUPPRESSED",
	}
	PreferenceState_value = map[string]int32{
		"PREFERENCE_STATE_UNSPECIFIED": 0,
		"PREFERENCE_STATE_ALLOWED":     1,
		"PREFERENCE_STATE_SUPPRESSED":  2,
	}
)

func (x PreferenceState) Enum() *PreferenceState {
	p := new(PreferenceState)
	*p = x
	return p
}

func (x PreferenceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreferenceState) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_enumTypes[0].Descriptor()
}

func (PreferenceState) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_enumTypes[0]
}

func (x PreferenceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreferenceState.Descriptor instead.
func (PreferenceState) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDescGZIP(), []int{0}
}

type PreferenceDecisionSource int32

const (
	PreferenceDecisionSource_PREFERENCE_DECISION_SOURCE_UNSPECIFIED PreferenceDecisionSource = 0
	PreferenceDecisionSource_PREFERENCE_DECISION_SOURCE_PROJECTION  PreferenceDecisionSource = 1
	PreferenceDecisionSource_PREFERENCE_DECISION_SOURCE_SERVICE     PreferenceDecisionSource = 2
)

// Enum value maps for PreferenceDecisionSource.
var (
	PreferenceDecisionSource_name = map[int32]string{
		0: "PREFERENCE_DECISION_SOURCE_UNSPECIFIED",
		1: "PREFERENCE_DECISION_SOURCE_PROJECTION",
		2: "PREFERENCE_DECISION_SOURCE_SERVICE",
	}
	PreferenceDecisionSource_value = map[string]int32{
		"PREFERENCE_DECISION_SOURCE_UNSPECIFIED": 0,
		"PREFERENCE_DECISION_SOURCE_PROJECTION":  1,
		"PREFERENCE_DECISION_SOURCE_SERVICE":     2,
	}
)

func (x PreferenceDecisionSource) Enum() *PreferenceDecisionSource {
	p := new(PreferenceDecisionSource)
	*p = x
	return p
}

func (x PreferenceDecisionSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreferenceDecisionSource) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_enumTypes[1].Descriptor()
}

func (PreferenceDecisionSource) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_enumTypes[1]
}

func (x PreferenceDecisionSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreferenceDecisionSource.Descriptor instead.
func (PreferenceDecisionSource) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDescGZIP(), []int{1}
}

type PreferenceDecisionReason int32

const (
	PreferenceDecisionReason_PREFERENCE_DECISION_REASON_UNSPECIFIED      PreferenceDecisionReason = 0
	PreferenceDecisionReason_PREFERENCE_DECISION_REASON_ALLOWED          PreferenceDecisionReason = 1
	PreferenceDecisionReason_PREFERENCE_DECISION_REASON_USER_OPTOUT      PreferenceDecisionReason = 2
	PreferenceDecisionReason_PREFERENCE_DECISION_REASON_TENANT_POLICY    PreferenceDecisionReason = 3
	PreferenceDecisionReason_PREFERENCE_DECISION_REASON_QUIET_HOURS      PreferenceDecisionReason = 4
	PreferenceDecisionReason_PREFERENCE_DECISION_REASON_CHANNEL_DISABLED PreferenceDecisionReason = 5
	PreferenceDecisionReason_PREFERENCE_DECISION_REASON_COMPLIANCE_HOLD  PreferenceDecisionReason = 6
)

// Enum value maps for PreferenceDecisionReason.
var (
	PreferenceDecisionReason_name = map[int32]string{
		0: "PREFERENCE_DECISION_REASON_UNSPECIFIED",
		1: "PREFERENCE_DECISION_REASON_ALLOWED",
		2: "PREFERENCE_DECISION_REASON_USER_OPTOUT",
		3: "PREFERENCE_DECISION_REASON_TENANT_POLICY",
		4: "PREFERENCE_DECISION_REASON_QUIET_HOURS",
		5: "PREFERENCE_DECISION_REASON_CHANNEL_DISABLED",
		6: "PREFERENCE_DECISION_REASON_COMPLIANCE_HOLD",
	}
	PreferenceDecisionReason_value = map[string]int32{
		"PREFERENCE_DECISION_REASON_UNSPECIFIED":      0,
		"PREFERENCE_DECISION_REASON_ALLOWED":          1,
		"PREFERENCE_DECISION_REASON_USER_OPTOUT":      2,
		"PREFERENCE_DECISION_REASON_TENANT_POLICY":    3,
		"PREFERENCE_DECISION_REASON_QUIET_HOURS":      4,
		"PREFERENCE_DECISION_REASON_CHANNEL_DISABLED": 5,
		"PREFERENCE_DECISION_REASON_COMPLIANCE_HOLD":  6,
	}
)

func (x PreferenceDecisionReason) Enum() *PreferenceDecisionReason {
	p := new(PreferenceDecisionReason)
	*p = x
	return p
}

func (x PreferenceDecisionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreferenceDecisionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_enumTypes[2].Descriptor()
}

func (PreferenceDecisionReason) Type() protoreflect.EnumType {
	return &file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_enumTypes[2]
}

func (x PreferenceDecisionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreferenceDecisionReason.Descriptor instead.
func (PreferenceDecisionReason) EnumDescriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDescGZIP(), []int{2}
}

var File_sh_whoa_sutradhar_preference_v1_preference_enums_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDesc = "" +
	"\n" +
	"6sh/whoa/sutradhar/preference/v1/preference_enums.proto\x12\x1fsh.whoa.sutradhar.preference.v1*r\n" +
	"\x0fPreferenceState\x12 \n" +
	"\x1cPREFERENCE_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PREFERENCE_STATE_ALLOWED\x10\x01\x12\x1f\n" +
	"\x1bPREFERENCE_STATE_SUPPRESSED\x10\x02*\x99\x01\n" +
	"\x18PreferenceDecisionSource\x12*\n" +
	"&PREFERENCE_DECISION_SOURCE_UNSPECIFIED\x10\x00\x12)\n" +
	"%PREFERENCE_DECISION_SOURCE_PROJECTION\x10\x01\x12&\n" +
	"\"PREFERENCE_DECISION_SOURCE_SERVICE\x10\x02*\xd5\x02\n" +
	"\x18PreferenceDecisionReason\x12*\n" +
	"&PREFERENCE_DECISION_REASON_UNSPECIFIED\x10\x00\x12&\n" +
	"\"PREFERENCE_DECISION_REASON_ALLOWED\x10\x01\x12*\n" +
	"&PREFERENCE_DECISION_REASON_USER_OPTOUT\x10\x02\x12,\n" +
	"(PREFERENCE_DECISION_REASON_TENANT_POLICY\x10\x03\x12*\n" +
	"&PREFERENCE_DECISION_REASON_QUIET_HOURS\x10\x04\x12/\n" +
	"+PREFERENCE_DECISION_REASON_CHANNEL_DISABLED\x10\x05\x12.\n" +
	"*PREFERENCE_DECISION_REASON_COMPLIANCE_HOLD\x10\x06B\xb3\x02\n" +
	"#com.sh.whoa.sutradhar.preference.v1B\x14PreferenceEnumsProtoP\x01ZUgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/preference/v1;preferencev1\xa2\x02\x04SWSP\xaa\x02\x1fSh.Whoa.Sutradhar.Preference.V1\xca\x02\x1fSh\\Whoa\\Sutradhar\\Preference\\V1\xe2\x02+Sh\\Whoa\\Sutradhar\\Preference\\V1\\GPBMetadata\xea\x02#Sh::Whoa::Sutradhar::Preference::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDesc), len(file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDescData
}

var file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_goTypes = []any{
	(PreferenceState)(0),          // 0: sh.whoa.sutradhar.preference.v1.PreferenceState
	(PreferenceDecisionSource)(0), // 1: sh.whoa.sutradhar.preference.v1.PreferenceDecisionSource
	(PreferenceDecisionReason)(0), // 2: sh.whoa.sutradhar.preference.v1.PreferenceDecisionReason
}
var file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_init() }
func file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_init() {
	if File_sh_whoa_sutradhar_preference_v1_preference_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDesc), len(file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_depIdxs,
		EnumInfos:         file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_enumTypes,
	}.Build()
	File_sh_whoa_sutradhar_preference_v1_preference_enums_proto = out.File
	file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_goTypes = nil
	file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_depIdxs = nil
}
