// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/preference/v1/preference_decision.proto

package preferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreferenceDecision struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	Allowed           bool                     `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason            PreferenceDecisionReason `protobuf:"varint,2,opt,name=reason,proto3,enum=sh.whoa.sutradhar.preference.v1.PreferenceDecisionReason" json:"reason,omitempty"`
	Source            PreferenceDecisionSource `protobuf:"varint,3,opt,name=source,proto3,enum=sh.whoa.sutradhar.preference.v1.PreferenceDecisionSource" json:"source,omitempty"`
	EvaluatedAt       *timestamppb.Timestamp   `protobuf:"bytes,4,opt,name=evaluated_at,json=evaluatedAt,proto3" json:"evaluated_at,omitempty"`
	ProjectionVersion int64                    `protobuf:"varint,5,opt,name=projection_version,json=projectionVersion,proto3" json:"projection_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PreferenceDecision) Reset() {
	*x = PreferenceDecision{}
	mi := &file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferenceDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferenceDecision) ProtoMessage() {}

func (x *PreferenceDecision) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferenceDecision.ProtoReflect.Descriptor instead.
func (*PreferenceDecision) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_rawDescGZIP(), []int{0}
}

func (x *PreferenceDecision) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *PreferenceDecision) GetReason() PreferenceDecisionReason {
	if x != nil {
		return x.Reason
	}
	return PreferenceDecisionReason_PREFERENCE_DECISION_REASON_UNSPECIFIED
}

func (x *PreferenceDecision) GetSource() PreferenceDecisionSource {
	if x != nil {
		return x.Source
	}
	return PreferenceDecisionSource_PREFERENCE_DECISION_SOURCE_UNSPECIFIED
}

func (x *PreferenceDecision) GetEvaluatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvaluatedAt
	}
	return nil
}

func (x *PreferenceDecision) GetProjectionVersion() int64 {
	if x != nil {
		return x.ProjectionVersion
	}
	return 0
}

var File_sh_whoa_sutradhar_preference_v1_preference_decision_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_rawDesc = "" +
	"\n" +
	"9sh/whoa/sutradhar/preference/v1/preference_decision.proto\x12\x1fsh.whoa.sutradhar.preference.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a6sh/whoa/sutradhar/preference/v1/preference_enums.proto\"\xc2\x02\n" +
	"\x12PreferenceDecision\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12Q\n" +
	"\x06reason\x18\x02 \x01(\x0e29.sh.whoa.sutradhar.preference.v1.PreferenceDecisionReasonR\x06reason\x12Q\n" +
	"\x06source\x18\x03 \x01(\x0e29.sh.whoa.sutradhar.preference.v1.PreferenceDecisionSourceR\x06source\x12=\n" +
	"\fevaluated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vevaluatedAt\x12-\n" +
	"\x12projection_version\x18\x05 \x01(\x03R\x11projectionVersionB\xb6\x02\n" +
	"#com.sh.whoa.sutradhar.preference.v1B\x17PreferenceDecisionProtoP\x01ZUgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/preference/v1;preferencev1\xa2\x02\x04SWSP\xaa\x02\x1fSh.Whoa.Sutradhar.Preference.V1\xca\x02\x1fSh\\Whoa\\Sutradhar\\Preference\\V1\xe2\x02+Sh\\Whoa\\Sutradhar\\Preference\\V1\\GPBMetadata\xea\x02#Sh::Whoa::Sutradhar::Preference::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_rawDesc), len(file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_rawDescData
}

var file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_goTypes = []any{
	(*PreferenceDecision)(nil),    // 0: sh.whoa.sutradhar.preference.v1.PreferenceDecision
	(PreferenceDecisionReason)(0), // 1: sh.whoa.sutradhar.preference.v1.PreferenceDecisionReason
	(PreferenceDecisionSource)(0), // 2: sh.whoa.sutradhar.preference.v1.PreferenceDecisionSource
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_depIdxs = []int32{
	1, // 0: sh.whoa.sutradhar.preference.v1.PreferenceDecision.reason:type_name -> sh.whoa.sutradhar.preference.v1.PreferenceDecisionReason
	2, // 1: sh.whoa.sutradhar.preference.v1.PreferenceDecision.source:type_name -> sh.whoa.sutradhar.preference.v1.PreferenceDecisionSource
	3, // 2: sh.whoa.sutradhar.preference.v1.PreferenceDecision.evaluated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_init() }
func file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_init() {
	if File_sh_whoa_sutradhar_preference_v1_preference_decision_proto != nil {
		return
	}
	file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_rawDesc), len(file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_preference_v1_preference_decision_proto = out.File
	file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_goTypes = nil
	file_sh_whoa_sutradhar_preference_v1_preference_decision_proto_depIdxs = nil
}
