// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sh/whoa/sutradhar/preference/v1/preference_event.proto

package preferencev1

import (
	v1 "github.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/common/v1"
	v11 "github.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/notification/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreferenceEvent struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	TenantContext   *v1.TenantContext       `protobuf:"bytes,1,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	RecipientRef    *v11.RecipientRef       `protobuf:"bytes,2,opt,name=recipient_ref,json=recipientRef,proto3" json:"recipient_ref,omitempty"`
	Channel         v11.NotificationChannel `protobuf:"varint,3,opt,name=channel,proto3,enum=sh.whoa.sutradhar.notification.v1.NotificationChannel" json:"channel,omitempty"`
	PreferenceState PreferenceState         `protobuf:"varint,4,opt,name=preference_state,json=preferenceState,proto3,enum=sh.whoa.sutradhar.preference.v1.PreferenceState" json:"preference_state,omitempty"`
	EffectiveFrom   *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`
	Version         int64                   `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreferenceEvent) Reset() {
	*x = PreferenceEvent{}
	mi := &file_sh_whoa_sutradhar_preference_v1_preference_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferenceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferenceEvent) ProtoMessage() {}

func (x *PreferenceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sh_whoa_sutradhar_preference_v1_preference_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferenceEvent.ProtoReflect.Descriptor instead.
func (*PreferenceEvent) Descriptor() ([]byte, []int) {
	return file_sh_whoa_sutradhar_preference_v1_preference_event_proto_rawDescGZIP(), []int{0}
}

func (x *PreferenceEvent) GetTenantContext() *v1.TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *PreferenceEvent) GetRecipientRef() *v11.RecipientRef {
	if x != nil {
		return x.RecipientRef
	}
	return nil
}

func (x *PreferenceEvent) GetChannel() v11.NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return v11.NotificationChannel(0)
}

func (x *PreferenceEvent) GetPreferenceState() PreferenceState {
	if x != nil {
		return x.PreferenceState
	}
	return PreferenceState_PREFERENCE_STATE_UNSPECIFIED
}

func (x *PreferenceEvent) GetEffectiveFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveFrom
	}
	return nil
}

func (x *PreferenceEvent) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_sh_whoa_sutradhar_preference_v1_preference_event_proto protoreflect.FileDescriptor

const file_sh_whoa_sutradhar_preference_v1_preference_event_proto_rawDesc = "" +
	"\n" +
	"6sh/whoa/sutradhar/preference/v1/preference_event.proto\x12\x1fsh.whoa.sutradhar.preference.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a0sh/whoa/sutradhar/common/v1/tenant_context.proto\x1a:sh/whoa/sutradhar/notification/v1/notification_enums.proto\x1a5sh/whoa/sutradhar/notification/v1/recipient_ref.proto\x1a6sh/whoa/sutradhar/preference/v1/preference_enums.proto\"\xc6\x03\n" +
	"\x0fPreferenceEvent\x12Q\n" +
	"\x0etenant_context\x18\x01 \x01(\v2*.sh.whoa.sutradhar.common.v1.TenantContextR\rtenantContext\x12T\n" +
	"\rrecipient_ref\x18\x02 \x01(\v2/.sh.whoa.sutradhar.notification.v1.RecipientRefR\frecipientRef\x12P\n" +
	"\achannel\x18\x03 \x01(\x0e26.sh.whoa.sutradhar.notification.v1.NotificationChannelR\achannel\x12[\n" +
	"\x10preference_state\x18\x04 \x01(\x0e20.sh.whoa.sutradhar.preference.v1.PreferenceStateR\x0fpreferenceState\x12A\n" +
	"\x0eeffective_from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\reffectiveFrom\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversionB\xb3\x02\n" +
	"#com.sh.whoa.sutradhar.preference.v1B\x14PreferenceEventProtoP\x01ZUgithub.com/whoa-sh/sutradhar/packages/go/sh/whoa/sutradhar/preference/v1;preferencev1\xa2\x02\x04SWSP\xaa\x02\x1fSh.Whoa.Sutradhar.Preference.V1\xca\x02\x1fSh\\Whoa\\Sutradhar\\Preference\\V1\xe2\x02+Sh\\Whoa\\Sutradhar\\Preference\\V1\\GPBMetadata\xea\x02#Sh::Whoa::Sutradhar::Preference::V1b\x06proto3"

var (
	file_sh_whoa_sutradhar_preference_v1_preference_event_proto_rawDescOnce sync.Once
	file_sh_whoa_sutradhar_preference_v1_preference_event_proto_rawDescData []byte
)

func file_sh_whoa_sutradhar_preference_v1_preference_event_proto_rawDescGZIP() []byte {
	file_sh_whoa_sutradhar_preference_v1_preference_event_proto_rawDescOnce.Do(func() {
		file_sh_whoa_sutradhar_preference_v1_preference_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_preference_v1_preference_event_proto_rawDesc), len(file_sh_whoa_sutradhar_preference_v1_preference_event_proto_rawDesc)))
	})
	return file_sh_whoa_sutradhar_preference_v1_preference_event_proto_rawDescData
}

var file_sh_whoa_sutradhar_preference_v1_preference_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sh_whoa_sutradhar_preference_v1_preference_event_proto_goTypes = []any{
	(*PreferenceEvent)(nil),       // 0: sh.whoa.sutradhar.preference.v1.PreferenceEvent
	(*v1.TenantContext)(nil),      // 1: sh.whoa.sutradhar.common.v1.TenantContext
	(*v11.RecipientRef)(nil),      // 2: sh.whoa.sutradhar.notification.v1.RecipientRef
	(v11.NotificationChannel)(0),  // 3: sh.whoa.sutradhar.notification.v1.NotificationChannel
	(PreferenceState)(0),          // 4: sh.whoa.sutradhar.preference.v1.PreferenceState
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_sh_whoa_sutradhar_preference_v1_preference_event_proto_depIdxs = []int32{
	1, // 0: sh.whoa.sutradhar.preference.v1.PreferenceEvent.tenant_context:type_name -> sh.whoa.sutradhar.common.v1.TenantContext
	2, // 1: sh.whoa.sutradhar.preference.v1.PreferenceEvent.recipient_ref:type_name -> sh.whoa.sutradhar.notification.v1.RecipientRef
	3, // 2: sh.whoa.sutradhar.preference.v1.PreferenceEvent.channel:type_name -> sh.whoa.sutradhar.notification.v1.NotificationChannel
	4, // 3: sh.whoa.sutradhar.preference.v1.PreferenceEvent.preference_state:type_name -> sh.whoa.sutradhar.preference.v1.PreferenceState
	5, // 4: sh.whoa.sutradhar.preference.v1.PreferenceEvent.effective_from:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sh_whoa_sutradhar_preference_v1_preference_event_proto_init() }
func file_sh_whoa_sutradhar_preference_v1_preference_event_proto_init() {
	if File_sh_whoa_sutradhar_preference_v1_preference_event_proto != nil {
		return
	}
	file_sh_whoa_sutradhar_preference_v1_preference_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sh_whoa_sutradhar_preference_v1_preference_event_proto_rawDesc), len(file_sh_whoa_sutradhar_preference_v1_preference_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sh_whoa_sutradhar_preference_v1_preference_event_proto_goTypes,
		DependencyIndexes: file_sh_whoa_sutradhar_preference_v1_preference_event_proto_depIdxs,
		MessageInfos:      file_sh_whoa_sutradhar_preference_v1_preference_event_proto_msgTypes,
	}.Build()
	File_sh_whoa_sutradhar_preference_v1_preference_event_proto = out.File
	file_sh_whoa_sutradhar_preference_v1_preference_event_proto_goTypes = nil
	file_sh_whoa_sutradhar_preference_v1_preference_event_proto_depIdxs = nil
}
